### ISSUE TITLE
com.crealytics.spark.excel.DefaultSource does not allow create table as select.

### ISSUE THREAD

**Issue by mdivk** [crealytics/spark-excel#106]
This issue was seen reported 2017, however, though I am using the latest version like below, it still throws error:
spark2-shell --packages com.crealytics:spark-excel_2.11:0.8.2

df.write 
  .format("com.crealytics.spark.excel") 
  //.option("dataAddress", "'My Sheet'!B3:C35") 
  .option("useHeader", "true") 
  .option("dateFormat", "yy-mmm-d") // Optional, default: yy-m-d h:mm 
    .option("timestampFormat", "mm-dd-yyyy hh:mm:ss") // Optional, default: yyyy-mm-dd hh:mm:ss.000 
  .mode("append") // Optional, default: overwrite. 
  .save("audit.xlsx")

df.show()
```
scala> df.show()
+---------+----------+-----------------+
|branch_id|dist_accts|              _c2|
+---------+----------+-----------------+
|   001659|         1|          4536.45|
|   880700|         1|           646.94|
|   008754|         2|             15.5|
|   008820|         2|          4329.82|
|   880565|         1|              0.0|
|   001746|         1|           454.13|
|   800415|         1|              0.0|
|   800202|         1|              0.0|
|   101029|         1|              0.0|
|   880694|         1|           681.63|
|   060022|         1|           909.34|
|   800284|         1|          1862.48|
|   001241|         1|          9171.86|
|   880573|         2|           1729.8|
|   001780|         1|            -0.79|
|   060700|         1|           866.01|
|   800421|         2|8154.120000000001|
|   001137|         1|              0.0|
|   060043|         1|              0.0|
|   060001|         2|          3499.45|
+---------+----------+-----------------+
only showing top 20 rows

Scala> df.write.format("com.crealytics.spark.excel").option("dataAddress", "'My Sheet'!B3:C35").option("useHeader", "true").option("dateFormat", "yy-mmm-d").option("timestampFormat", "mm-dd-yyyy hh:mm:ss").mode("append").save("v201812_audit_dim_gaps.xlsx")
java.lang.RuntimeException: com.crealytics.spark.excel.DefaultSource does not allow create table as select.
  at scala.sys.package$.error(package.scala:27)
  at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:476)
  at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:610)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:233)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:217)
  ... 50 elided

```
Environment:
version 2.2.0.cloudera1, Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_131)

It would be greatly appreciated if anyone can shed me with more light on the fix, thank you in advance.

**Comment by nightscape** [comment]
According to your command, you're using a quite outdated version (0.11.0 is the newest):
```
spark2-shell --packages com.crealytics:spark-excel_2.11:0.8.2
```
