### ISSUE TITLE
Error is not descriptive enough

### ISSUE THREAD

**Issue by hoangelos** [crealytics/spark-excel#108]
I'm using the following versions
spark-excel: 0.11.0
Scala: 2.11.12
Spark: 2.4.0

I'm trying to load up an xlsx file, but I get an error that is very vague.  

```
scala> val df = sqlContext.read.format("com.crealytics.spark.excel").option("useHeader", "true").option("inferSchema", "true").load("/Users/halliday/heirloom-equity-importer/TaxLien.xlsx")
19/01/30 23:02:47 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/Users/halliday/heirloom-equity-importer/spark-warehouse').
19/01/30 23:02:47 INFO SharedState: Warehouse path is 'file:/Users/halliday/heirloom-equity-importer/spark-warehouse'.
19/01/30 23:02:48 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
scala.MatchError: Map(useheader -> true, inferschema -> true, path -> /Users/halliday/heirloom-equity-importer/TaxLien.xlsx) (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap)
  at com.crealytics.spark.excel.DataLocator$.apply(DataLocator.scala:52)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:29)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
  ... 42 elided
```

**Comment by hoangelos** [comment]
So, I upgraded to 0.11.1, and this went away.  Apparently, there was a requirement to use dataAddress previous to that, which I didn't realize.

**Comment by nightscape** [comment]
Exactly, I fixed that yesterday as lots and lots of people stumbled over it.
