### ISSUE TITLE
Issue with dependencies

### ISSUE THREAD

**Issue by donthusa** [crealytics/spark-excel#113]
I am using 0.8.5 version and getting following error when I try to add my own schema:

Caused by: java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Cell.getCellTypeEnum()Lorg/apache/poi/ss/usermodel/CellType;
	at com.crealytics.spark.excel.ExcelRelation.com$crealytics$spark$excel$ExcelRelation$$castTo(ExcelRelation.scala:86)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$1$$anonfun$3.apply(ExcelRelation.scala:62)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$1$$anonfun$3.apply(ExcelRelation.scala:62)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$1$$anonfun$apply$3.apply(ExcelRelation.scala:75)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$1$$anonfun$apply$3.apply(ExcelRelation.scala:70)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$5$$anonfun$apply$4.apply(ExcelRelation.scala:79)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$5$$anonfun$apply$4.apply(ExcelRelation.scala:79)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$5.apply(ExcelRelation.scala:79)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$5.apply(ExcelRelation.scala:79)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:732)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:708)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)

*Code snippet*

val peopleSchema = StructType(Array(
      StructField("Gtin", StringType, nullable = false),
      StructField("Store", StringType, nullable = false),
      StructField("LineNumber", StringType, nullable = false),
      StructField("Dates", DateType, nullable = false)))

The names mentioned match the column names in the Excel file.
val df = spark.read
      .format("com.crealytics.spark.excel")      
      .option("useHeader", "true")
      .schema(peopleSchema)
      .load("Book1.xlsx")

Note: I have poi, poi-ooxml(version - 3.14-beta1) dependencies in my pom which I need for other functionalities to work, Scala version: 2.11.8,  Spark Version:2.3.0

**Comment by nightscape** [comment]
Have you tried newer versions?
0.8.5 is ancient :wink:

**Comment by donthusa** [comment]
Yes, I have. But of no use. One more quick thing - Where can I find the documentation for the complete list of options supported for each version?

**Comment by nightscape** [comment]
You'd have to dig through the Git history of README.md for that...

**Comment by donthusa** [comment]
The latest version used Apache POI 4.0. What is the latest version which uses Apache POI 3.17 or 3.16? My rest of the code uses POI 3.17 functionalities that are deprecated in Apache POI 4.0

**Comment by nightscape** [comment]
Afair 0.9.? was the last version using POI 3.x
You'd have to check the Git history of build.sbt though.

**Comment by donthusa** [comment]
Checked. It is 0.9.15. Thanks! How can I read the file on HDFS? Will the location option accept HDFS URI?

**Comment by nightscape** [comment]
It should.
