### ISSUE TITLE
Could not initialize class com.crealytics.spark.excel.WorkbookReader$

### ISSUE THREAD

**Issue by sslyle** [crealytics/spark-excel#130]
This error:
java.lang.NoClassDefFoundError: Could not initialize class com.crealytics.spark.excel.WorkbookReader$

This code:
%scala
// this throws the same error ~ 
//val df = spark.read.excel(useHeader = false)
//   .load("/mnt/myexcelfile.xlsx")

val df = sqlContext.read.format("com.crealytics.spark.excel")
  .option("location", "/mnt/myexcelfile.xlsx")
  .option("useHeader", "False") // same error with or without useHeader
  .load()

This environment;
Databricks Runtime Version 5.3 (Scala 2.11, Spark 2.4.1) & Python Version 3 (3.5)
8 Workers: 112.0 GB Memory, 32 Cores, 6 DBU
1 Driver: 14.0 GB Memory, 4 Cores, 0.75 DBU

This Maven Coordinate installed using the Maven library installer provided by the cluster without any issue, no exclusions & no dependencies reported:
com.crealytics:spark-excel_2.12:0.12.0

I find no other relevant case on the inet or this Git regarding this problem.
I have no where else to turn except to a different library, perhaps Python.

**Comment by nightscape** [comment]
Can you paste the entire stacktrace?
Also, check what happens if you just do a
```scala
import com.crealytics.spark.excel.WorkbookReader
```

**Comment by sslyle** [comment]
Sure & thanks for the response.

Here is the full stacktrace after having added the `import`.
The import did not change the error.
I didn't recognize anything helpful in the stacktrace.

java.lang.NoClassDefFoundError: Could not initialize class com.crealytics.spark.excel.WorkbookReader$
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:28)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:346)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:291)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:277)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:201)
	at line4a75e368050c475a93d6401bc196900735.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-3554487056298171:5)
	at line4a75e368050c475a93d6401bc196900735.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-3554487056298171:72)
	at line4a75e368050c475a93d6401bc196900735.$read$$iw$$iw$$iw$$iw.<init>(command-3554487056298171:74)
	at line4a75e368050c475a93d6401bc196900735.$read$$iw$$iw$$iw.<init>(command-3554487056298171:76)
	at line4a75e368050c475a93d6401bc196900735.$read$$iw$$iw.<init>(command-3554487056298171:78)
	at line4a75e368050c475a93d6401bc196900735.$read$$iw.<init>(command-3554487056298171:80)
	at line4a75e368050c475a93d6401bc196900735.$read.<init>(command-3554487056298171:82)
	at line4a75e368050c475a93d6401bc196900735.$read$.<init>(command-3554487056298171:86)
	at line4a75e368050c475a93d6401bc196900735.$read$.<clinit>(command-3554487056298171)
	at line4a75e368050c475a93d6401bc196900735.$eval$.$print$lzycompute(<notebook>:7)
	at line4a75e368050c475a93d6401bc196900735.$eval$.$print(<notebook>:6)
	at line4a75e368050c475a93d6401bc196900735.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:199)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:590)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:545)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:323)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:303)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:235)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:230)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:47)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:268)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:47)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:303)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:591)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:591)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:586)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:477)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:544)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:383)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:330)

**Comment by nightscape** [comment]
Ah, wait. You're using the `spark-excel_2.12` version with a Scala 2.11 Spark.
That can't work...

**Comment by sslyle** [comment]
So what is most recent and permissable?

**Comment by sslyle** [comment]
Okay.
This works using spark-excel_2.11:0.11.1
import com.crealytics.spark.excel
var df = spark.read.excel(useHeader = false).load("/mnt/myexcelfile.xlsx")

But this does not (not that I need it to):
import com.crealytics.spark.excel
var df = sqlContext.read.format("com.crealytics.spark.excel").option("location", "/mnt/myexcelfile.xlsx").option("useHeader", "False").load()

error:

scala.MatchError: Map(location -> /mnt/myexcelfile.xlsx, useheader -> False) (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap)
	at com.crealytics.spark.excel.WorkbookReader$.apply(WorkbookReader.scala:30)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:28)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:346)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:291)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:277)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:201)
	at line36ec04753d1747d8b3d069e4751de87f118.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-3554487056298171:2)
	at line36ec04753d1747d8b3d069e4751de87f118.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-3554487056298171:89)
	at line36ec04753d1747d8b3d069e4751de87f118.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-3554487056298171:91)
	at line36ec04753d1747d8b3d069e4751de87f118.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-3554487056298171:93)
	at line36ec04753d1747d8b3d069e4751de87f118.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-3554487056298171:95)
	at line36ec04753d1747d8b3d069e4751de87f118.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-3554487056298171:97)
	at line36ec04753d1747d8b3d069e4751de87f118.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-3554487056298171:99)
	at line36ec04753d1747d8b3d069e4751de87f118.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-3554487056298171:101)
	at line36ec04753d1747d8b3d069e4751de87f118.$read$$iw$$iw$$iw$$iw.<init>(command-3554487056298171:103)
	at line36ec04753d1747d8b3d069e4751de87f118.$read$$iw$$iw$$iw.<init>(command-3554487056298171:105)
	at line36ec04753d1747d8b3d069e4751de87f118.$read$$iw$$iw.<init>(command-3554487056298171:107)
	at line36ec04753d1747d8b3d069e4751de87f118.$read$$iw.<init>(command-3554487056298171:109)
	at line36ec04753d1747d8b3d069e4751de87f118.$read.<init>(command-3554487056298171:111)
	at line36ec04753d1747d8b3d069e4751de87f118.$read$.<init>(command-3554487056298171:115)
	at line36ec04753d1747d8b3d069e4751de87f118.$read$.<clinit>(command-3554487056298171)
	at line36ec04753d1747d8b3d069e4751de87f118.$eval$.$print$lzycompute(<notebook>:7)
	at line36ec04753d1747d8b3d069e4751de87f118.$eval$.$print(<notebook>:6)
	at line36ec04753d1747d8b3d069e4751de87f118.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:199)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:590)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:545)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:323)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:303)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:235)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:230)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:47)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:268)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:47)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:303)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:591)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:591)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:586)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:477)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:544)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:383)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:330)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:216)
	at java.lang.Thread.run(Thread.java:748)

**Comment by nightscape** [comment]
Yes, the `option("location", ...)` version is old. Sounds like this can be closed.

**Comment by sslyle** [comment]
Agree to close this
