### ISSUE TITLE
"java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC cell" when numeric values in header

### ISSUE THREAD

**Issue by saadali5997** [crealytics/spark-excel#137]
This issue is [there](https://github.com/crealytics/spark-excel/issues/7) in `closed` issues, no reason given of why it was closed. It's still not resolved.
This issue is also mentioned [here](https://stackoverflow.com/questions/48301217/spark-excel-dataype-issues).

## Expected Behavior
Ideally
```
val df = spark.read.format("com.crealytics.spark.excel").option("useHeader", "true").option("inferSchema", "true").load("test.xls")
```
should read the excel file normally.

## Current Behavior
Whenever I try to read the file, this exception occurs:
```
java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC cell
  at shadeio.poi.hssf.usermodel.HSSFCell.typeMismatch(HSSFCell.java:635)
  at shadeio.poi.hssf.usermodel.HSSFCell.getRichStringCellValue(HSSFCell.java:712)
  at shadeio.poi.hssf.usermodel.HSSFCell.getStringCellValue(HSSFCell.java:695)
  at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1$$anonfun$11.apply(ExcelRelation.scala:149)
  at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1$$anonfun$11.apply(ExcelRelation.scala:149)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:149)
  at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:147)
  at scala.Option.getOrElse(Option.scala:121)
  at com.crealytics.spark.excel.ExcelRelation.inferSchema(ExcelRelation.scala:147)
  at com.crealytics.spark.excel.ExcelRelation.<init>(ExcelRelation.scala:40)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:40)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:340)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:174)
```
The error got resolved when I manually changed all first-row-cell-values to strings instead of integers.

## Possible Solution
Convert non-string column names to string while reading?

## Steps to Reproduce (for bugs)
Try reading [this](https://sample-videos.com/xls/Sample-Spreadsheet-100-rows.xls) excel file.
I tried reading this with `.option("inferSchema", "true")` as well as `.option("inferSchema", "false")` but the exception kept on happening.

## Context
I was just trying to read an excel file using this library.

## Your Environment
I am using `Zeppelin` notebook to run this. The code above is the first line of my project.
I am using the following versions:
Apache Spark => `2.3`
Spark-excel => `0.12.0` from [here](https://mvnrepository.com/artifact/com.crealytics/spark-excel_2.11/0.12.0).

**Comment by nightscape** [comment]
Currently, it is assumed that headers are String cells.
To change this, you could extract the [two `val`s here](https://github.com/crealytics/spark-excel/blob/master/src/main/scala/com/crealytics/spark/excel/ExcelRelation.scala#L148-L149) into `lazy val`s at the class level and change [this line](https://github.com/crealytics/spark-excel/blob/master/src/main/scala/com/crealytics/spark/excel/ExcelRelation.scala#L35) to `zip` the two values.
If you create a PR along with tests, I'd be happy to review :+1:

**Comment by saadali5997** [comment]
@nightscape okay, makes sense but it still does not explain it not working when I do
```
.option("useHeader", "false")
```
Ideally, it should just not read the first row as header when I use that option, right? So the problem is not just the code assuming headers are `String` cell, it's actually assumed that first row never has non-string cells which is not right I believe.
Would the fix you suggested above fix this problem too?

**Comment by nightscape** [comment]
In your initial description you mentioned that you tried `.option("inferSchema", "true")` as well as `.option("inferSchema", "false")`. So it also doesn't work with `.option("useHeader", "false")`?
Can you also try with `.option("inferSchema", "false").option("useHeader", "false")` to narrow down the problem?

**Comment by saadali5997** [comment]
@nightscape I did try this and double checked, it still does NOT work. Same exception again.

**Comment by nightscape** [comment]
The problem is that the `inferSchema` method gets called independently of the `useHeader` option and it immediately reads the header row as Strings.
There is some restructuring necessary in order to make this work, including the `makeSafeHeader` method. Unfortunately I can't invest any time in this, so someone would need to write a PR.

**Comment by saadali5997** [comment]
I am an year experienced developing applications in Scala. I know you must be a very busy person, but IF you could guide me a little what to do, where to do, I could do that work in my extra time. Again, IF you get time. 
For now, in my applications, I am doing what I need using apache poi as this didn't work,

**Comment by sslyle** [comment]
You know an error like this SHOULD NEVER HAPPEN.
What the heck can't read a int/decimal/numeric as a string?

How do I force all values of all cells to be read as string?
Because I'm sure I can do better converting from strings for myself than anything else going on with this tool.

In fact you might think about that.  
Just read all cell values as strings.  
If you make that happen then your tool will never be more adoptable.
But right now as you work on your tool you are trying to second guess everything Microsoft has going on in their Excel file.  You are trying to beat Microsoft at their game.  Not great strategy.  Because they certainly don't care how much you fail.  And you are entirely dependent on everything they do to Excel.

And let's not forget what they say about assume, "assumes header is all strings"

**Comment by EnverOsmanov** [comment]
Similar issue: https://github.com/crealytics/spark-excel/issues/117

**Comment by nightscape** [comment]
I've changed the header handling logic in `0.12.2`.
Can you give that a try and see if it works?

**Comment by EnverOsmanov** [comment]
On my example it worked.

**Comment by xjhjzxh** [comment]
I use 0.12.3, it works, this problem fixed, very thanks

**Comment by Qurashetufail** [comment]
I am facing this issue on version 0.13.0. Below is my code snippet
Hi,
```
	val clm = sqlContext.read
		.format("com.crealytics.spark.excel")
		.option("dataAddress", "RLD_CLAIM!B3:C35")
		.option("header", "true") // Required
		.option("treatEmptyValuesAsNulls", "false") 
		.option("inferSchema", "false") 
		.load("data/input/batch/file.xlsx")
		.select("claim_id_seq","customer_name")
```
I also tried it on `version 0.12.3`. I am using `spark version 2.2.2` 

Thanks.
Tufail

**Comment by A5H1Q** [comment]
> On my example it worked.

which version are you using. I'm getting the same error (`java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC cell`) with version `com.crealytics:spark-excel-2.12.17-3.2.2_2.12 : 3.2.2_0.18.1`
