### ISSUE TITLE
Issue while reading Xlsx file from azure blob storage.

### ISSUE THREAD

**Issue by AyubmmD** [crealytics/spark-excel#150]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior
Below is the code  snippet I used after following the official documentation of databricks.

spark.conf.set("fs.azure.account.key.<storage-account-name>.blob.core.windows.net","<storage-account-access-key>")

 val xlxfile = spark.read .format("com.crealytics.spark.excel")
      .option("sheetName", "Sheet1")
      .option("useHeader", "true")
      .option("treatEmptyValuesAsNulls", "false")
      .option("inferSchema", "true")
      .option("location", path)
      .option("addColorColumns", "false")

## Current Behavior
> **The below error comes**.
Configuration property  xxxxxxxxxx.dfs.core.windows.net not found.
I did a dig dive on the spark-excel code . Its throwing in the code : 
      FileSystem.get(path.toUri, hadoopConfiguration).open(path)

[Object WorkbookReader, line number 28](https://github.com/crealytics/spark-excel/blob/v0.11.1/src/main/scala/com/crealytics/spark/excel/WorkbookReader.scala).

**Below is the stacktrace:** 
  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
at com.crealytics.spark.excel.WorkbookReader$.com$crealytics$spark$excel$WorkbookReader$$readFromHadoop$1(WorkbookReader.scala:28)
at com.crealytics.spark.excel.WorkbookReader$$anonfun$apply$2.apply(WorkbookReader.scala:34)
at com.crealytics.spark.excel.WorkbookReader$$anonfun$apply$2.apply(WorkbookReader.scala:34)
at com.crealytics.spark.excel.DefaultWorkbookReader$$anonfun$openWorkbook$1.apply(WorkbookReader.scala:42)
at com.crealytics.spark.excel.DefaultWorkbookReader$$anonfun$openWorkbook$1.apply(WorkbookReader.scala:42)
at scala.Option.fold(Option.scala:158)
at com.crealytics.spark.excel.DefaultWorkbookReader.openWorkbook(WorkbookReader.scala:42)
at com.crealytics.spark.excel.WorkbookReader$class.withWorkbook(WorkbookReader.scala:14)
at com.crealytics.spark.excel.DefaultWorkbookReader.withWorkbook(WorkbookReader.scala:38)
at com.crealytics.spark.excel.ExcelRelation.buildScan(ExcelRelation.scala:75)

.

## Steps to Reproduce (for bugs)
Put a xlsx file in azure blob storage and try to read it as mentioned above. Don't try mounting . Directly try accessing azure blob.

## Context
I am not able to read and work with xlsx file from azure blob.

## Your Environment
> Include as many relevant details about the environment you experienced the bug in
* Spark version and language (Scala, Java, Python, R, ...): scala 2.11, spark 2.3
* Spark-Excel version: 0.11.1
* Operating System and version, cluster environment, ...: Databricks .

**Comment by AyubmmD** [comment]
@nightscape

**Comment by AyubmmD** [comment]
spark.sparkcontext.hadoopconfiguration.set("fs.azure.account.key..blob.core.windows.net","") , fixed the problem.

**Comment by nightscape** [comment]
Ah, great to know! Thanks for getting back and posting the solution here 👍

**Comment by AyubmmD** [comment]
No worries, may help others if facing the same error.
