### ISSUE TITLE
Failed to load excel to df 

### ISSUE THREAD

**Issue by eldindevassy** [crealytics/spark-excel#207]
Caused by: scala.MatchError: Map(treatemptyvaluesasnulls -> true, location -> C:\Users\user1\Desktop\myfile.xlsx, useheader -> true, inferschema -> true, addcolorcolumns -> false, sheetname -> test) (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap)
	at com.crealytics.spark.excel.WorkbookReader$.apply(WorkbookReader.scala:38)
at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:28)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)

Getting above exception while trying to load an excel.

Version details below.
    <groupId>com.crealytics</groupId>
    <artifactId>spark-excel_2.11</artifactId>
    <version>0.12.5</version>

Code:
val df = sparkSession.read
    .format("com.crealytics.spark.excel")
    .option("useHeader", "true")
    .load("path_to_excel")

**Comment by nightscape** [comment]
Can you try adding the `dataAddress` option manually? It should have a default, but it seems that isn't working...

**Comment by eldindevassy** [comment]
Thank you. It worked. Do you know why it didn't take default.?

**Comment by nightscape** [comment]
Probably some stupid mistake I made 😉
Will fix it when I find the time.
Unless you want to give it a try 😃

**Comment by eldindevassy** [comment]
Something weird happened. It seems to be working now even without 'DataAddress'. 
Even WorkbookReader(params).sheetNames is working now. I was getting same exception for this method. I tried to recreate this issue. But no luck. Maybe we can close this issue now and  reopen if I face it again. Thoughts?

**Comment by nightscape** [comment]
Sounds good :)
