### ISSUE TITLE
Scala Match Error 

### ISSUE THREAD

**Issue by ryangamadia** [crealytics/spark-excel#208]
I have 2 excel sheets (same format, same schema) that I am converting to a dataframe. The first excel sheet loaded perfectly fine. Both excel sheets contain blanks cells, and I have inferschema set to true. However, I get this error below when I try to load the second excel sheet. 

Not sure if there is something wrong with one row -- is there a way to tell which row or column the error in the data is happening? 

`scala.MatchError: ERROR (of class shadeio.poi.ss.usermodel.CellType)`

`at com.crealytics.spark.excel.ExcelRelation.com$crealytics$spark$excel$ExcelRelation$$getSparkType(ExcelRelation.scala:84)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7$$anonfun$9$$anonfun$apply$7$$anonfun$apply$9.apply(ExcelRelation.scala:110)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7$$anonfun$9$$anonfun$apply$7$$anonfun$apply$9.apply(ExcelRelation.scala:110)
	at scala.Option.map(Option.scala:146)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7$$anonfun$9$$anonfun$apply$7.apply(ExcelRelation.scala:110)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7$$anonfun$9$$anonfun$apply$7.apply(ExcelRelation.scala:110)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7$$anonfun$9.apply(ExcelRelation.scala:110)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7$$anonfun$9.apply(ExcelRelation.scala:109)
	at scala.collection.immutable.List.map(List.scala:284)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7.apply(ExcelRelation.scala:109)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7.apply(ExcelRelation.scala:105)
	at scala.Option.getOrElse(Option.scala:121)
	at com.crealytics.spark.excel.ExcelRelation.headerColumns$lzycompute(ExcelRelation.scala:105)
	at com.crealytics.spark.excel.ExcelRelation.headerColumns(ExcelRelation.scala:104)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:162)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:161)
	at scala.Option.getOrElse(Option.scala:121)
	at com.crealytics.spark.excel.ExcelRelation.inferSchema(ExcelRelation.scala:161)
	at com.crealytics.spark.excel.ExcelRelation.<init>(ExcelRelation.scala:35)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:40)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:347)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:307)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:293)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:214)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$anonfun$1$$anonfun$apply$1.apply(command-4306809369424782:22)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$anonfun$1$$anonfun$apply$1.apply(command-4306809369424782:7)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$anonfun$1.apply(command-4306809369424782:7)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$anonfun$1.apply(command-4306809369424782:5)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:5)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:100)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:102)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:104)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:106)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:108)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:110)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:112)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:114)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw.<init>(command-4306809369424782:116)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw.<init>(command-4306809369424782:118)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw.<init>(command-4306809369424782:120)
	at linefbdb2b3d70b8425092601e89614a415a106.$read.<init>(command-4306809369424782:122)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$.<init>(command-4306809369424782:126)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$.<clinit>(command-4306809369424782)
	at linefbdb2b3d70b8425092601e89614a415a106.$eval$.$print$lzycompute(<notebook>:7)
	at linefbdb2b3d70b8425092601e89614a415a106.$eval$.$print(<notebook>:6)
	at linefbdb2b3d70b8425092601e89614a415a106.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:215)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:700)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:653)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$9.apply(DriverLocal.scala:386)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$9.apply(DriverLocal.scala:363)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:235)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:230)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:49)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:272)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:49)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:363)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:639)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:485)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:597)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:390)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)`

## Your Environment
> 
* Spark version and language Scala 2.11, Spark 2.4.4
* Spark-Excel version: com.crealytics:spark-excel_2.11:0.12.4
* Operating System and version, cluster environment: Databricks Runtime 6.1, Standard Cluster Mode

Worker Type:
14.0 GB Memory, 4 Cores, 0.75 DBU
Standard_DS3_v2
Min Workers: 2 Max Workers: 8

Driver Type:
14.0 GB Memory, 4 Cores, 0.75 DBU
Standard_DS3_v2

**Comment by nightscape** [comment]
Right, there actually is no handling of cells with type `ERROR`:
https://github.com/crealytics/spark-excel/blob/master/src/main/scala/com/crealytics/spark/excel/ExcelRelation.scala#L84-L95
One could either return them as `null` or abort the entire process with a more understandable error.
Would you mind creating a PR?

**Comment by derianpt** [comment]
Hi all, we are coming across this error in our application as well. The root cause is the excel contains cells with `ERROR` values such as `#N/A`. Our preferred solution for this to process the cell as `STRING` type & output `#N/A` in the parquet. 

My suggestion is to add a new read option:
`.option("treatErrorsAsStrings", "false") // Optional, default: false, If true, read cell values as strings. Otherwise, they will be converted to null.`

Wdyt? @nightscape

**Comment by nightscape** [comment]
@derianpt that sounds reasonable 👍 
Would you mind creating a PR?

**Comment by derianpt** [comment]
Hi @nightscape, I have created a draft PR above. Will continue the discussion there.
