### ISSUE TITLE
Issues with date column in excel

### ISSUE THREAD

**Issue by dzlab** [crealytics/spark-excel#220]
I have an issue with parsing dates on a file where dates are stored as numbers (e.g. `42737.0`).

## Expected Behavior
This is a bug, Excel dates should have been parsed as Spark Date data type when schema inference is ued.

## Current Behavior
If I try to read the excel file without inferring schema like following I get back a `DataFrame` with the double values 
```scala
        sqlContext.read.format("com.crealytics.spark.excel").options(
          Map(
            "useHeader" -> (if (hasHeader) "true" else "false"),
            "treatEmptyValuesAsNulls" -> "false",
            "inferSchema" -> "false"
          )
        ).load(filePath)
```
If I try to infer schema (i.e. `"inferSchema" -> "true"`), I get exception when read from the `DataFrame`
```
Caused by: java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: java.lang.Double is not a valid external type for schema of string
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 0, Date), StringType), true, false) AS Date#12
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 1, Number), StringType), true, false) AS Number#13
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:292)
	at org.apache.spark.sql.SparkSession$$anonfun$4.apply(SparkSession.scala:593)
	at org.apache.spark.sql.SparkSession$$anonfun$4.apply(SparkSession.scala:593)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:256)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.Double is not a valid external type for schema of string
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.StaticInvoke_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:289)
	... 19 more
```

Also if I put a break point here [ExcelRelation.scala#L93](https://github.com/crealytics/spark-excel/blob/master/src/main/scala/com/crealytics/spark/excel/ExcelRelation.scala#L93), it seems that values like `42737.0` are not recognized as Dates (`DateUtil.isCellDateFormatted` returns false).

I also found that such cell has a [format index](https://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/BuiltinFormats.html) of `164`, and a format string that looks like this `B1d\-mmm\-yy`. Those seems to come from the cell style which is an instance of `XSSFCellStyle`. When debugging and inspecting this instance I see the following values for each of its properties:
```
_cellXf = "<xml-fragment numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1" applyAlignment="1" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac" xmlns:x16r2="http://schemas.microsoft.com/office/spreadsheetml/2015/02/main" xmlns:xr="http://schemas.microsoft.com/office/spreadsheetml/2014/revision"/>"

_cellStyleXf = "<xml-fragment numFmtId="0" fontId="0" fillId="0" borderId="0" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac" xmlns:x16r2="http://schemas.microsoft.com/office/spreadsheetml/2015/02/main" xmlns:xr="http://schemas.microsoft.com/office/spreadsheetml/2014/revision"/>"

_stylesSource = "Name: /xl/styles.xml - Content Type: application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"
```

## Possible Solution
Not sure what is the proper way to read Excel files containing dates?

## Steps to Reproduce (for bugs)
Have an excel file with a column that have dates and try to read it with code snippet above.

**Comment by nightscape** [comment]
Can you fill in more details as specified in the [`ISSUE_TEMPLATE`](https://github.com/crealytics/spark-excel/blob/master/ISSUE_TEMPLATE.md)?

**Comment by dzlab** [comment]
@nightscape I updated the issue, wonder if that explains better.

**Comment by nightscape** [comment]
@dzlab the important parts are still missing 😉 
I've adapted the issue template a little to make it clearer.
My guess is that you're using a newer version of spark-excel where the `useHeader` parameter was renamed to `header` which could lead to such an effect, but I can't tell because the required information is missing from the bug report:

## Steps to Reproduce (for bugs)
> Provide a link to a live example, or an unambiguous set of steps to
> reproduce this bug. Include code to reproduce, if relevant.
> Example:
1. Download the example file uploaded [here](http://example.com/)
2. Start Spark from command line as `spark-shell --packages com.crealytics:spark-excel_2.12:x.y.z --foo=bar`
3. Read the downloaded example file
    ```
    val df = spark.read
    .format("com.crealytics.spark.excel")
    .option("dataAddress", "'My Sheet'!B3:C35")
    .load("example_file_exhibiting_bug.xlsx")
    ```

## Your Environment
> Include as many relevant details about the environment you experienced the bug in
* Spark version and language (Scala, Java, Python, R, ...):
* Spark-Excel version:
* Operating System and version, cluster environment, ...:

**Comment by dzlab** [comment]
It turns out the date column was formatted as custom format and not dates, this why the format index was 164 which is out of range for dates. Formatting the date column as date fixed the issue.
