### ISSUE TITLE
maxRowsInMemory can cause rows to be dropped

### ISSUE THREAD

**Issue by jamthoma** [crealytics/spark-excel#223]
I have a relatively large xls that causes memory issues, so I tried to use "maxRowsInMemory".
Unfortunately, this caused most of the rows to get dropped.
I puled the source code and uncommented the exception in ExcelRelation.scala (line 73).
The exception below was observed.

Basically, version 2.1.0 of xlsx-streamer does not implement "getSheet", which is used by POI DataFormatter.

The latest code in xlsx-streamer has implemented the "getSheet" API, so once it's released this issue will hopefully be resolved by increasing the xlsx-streamer dependency version.

> shadeio.monitorjbl.xlsx.exceptions.NotSupportedException
        at shadeio.monitorjbl.xlsx.impl.StreamingCell.getSheet(StreamingCell.java:330)
        at shadeio.poi.ss.usermodel.DataFormatter.isDate1904(DataFormatter.java:313)
        at shadeio.poi.ss.usermodel.DataFormatter.getFormat(DataFormatter.java:309)
        at shadeio.poi.ss.usermodel.DataFormatter.getFormattedNumberString(DataFormatter.java:858)
        at shadeio.poi.ss.usermodel.DataFormatter.formatCellValue(DataFormatter.java:1011)
        at shadeio.poi.ss.usermodel.DataFormatter.formatCellValue(DataFormatter.java:961)
        at shadeio.poi.ss.usermodel.DataFormatter.formatCellValue(DataFormatter.java:940)
        at com.crealytics.spark.excel.HeaderDataColumn.stringValue$lzycompute$1(DataColumn.scala:43)
        at com.crealytics.spark.excel.HeaderDataColumn.stringValue$1(DataColumn.scala:33)
        at com.crealytics.spark.excel.HeaderDataColumn.extractValue(DataColumn.scala:79)
        at com.crealytics.spark.excel.DataColumn$class.apply(DataColumn.scala:16)
        at com.crealytics.spark.excel.HeaderDataColumn.apply(DataColumn.scala:19)
        at com.crealytics.spark.excel.HeaderDataColumn.apply(DataColumn.scala:19)
'

**Comment by nightscape** [comment]
Hi @jamthoma, nice find!
I think @scala-steward should let us know once the new version of `xlsx-streamer` hits Maven :+1:

**Comment by karamveer-scala** [comment]
@nightscape  

I am facing issue reading an excel file of size 25 mb by crealytics library. I am using simple spark job to read excel but i get GC Overhead error issue .
I referred code from your git repository-
https://github.com/crealytics/spark-excel

Kindly help me to overcome this issue

**Comment by nightscape** [comment]
Hi @karamveer-scala, if you're not getting the same error as described here, please create a new issues and fill out everything that is asked in the issue template you should see when creating the issue.

**Comment by nightscape** [comment]
@pjfanning does your fork already include the implementation of `StreamingCell#getSheet`?
It might be a good time to switch to your fork which is much more actively maintained.
Apart from not having support for Java < 8 are there any known negative consequences?

**Comment by pjfanning** [comment]
@nightscape my fork does implement StreamingCell#getSheet

**Comment by pjfanning** [comment]
@jamthoma xlsx-streamer is not compatible with the latest versions of POI, you will need to use POI 4.1.0 but not POI 4.1.1 or 4.1.2

**Comment by nightscape** [comment]
Could someone try `0.13.2+1-e186f935-SNAPSHOT`? It's based on @pjfanning's fork of `excel-stream-reader` and might fix this problem (wishful thinking :wink:).

**Comment by pjfanning** [comment]
This issue might be related to https://github.com/monitorjbl/excel-streaming-reader/issues/176

**Comment by jamthoma** [comment]
@nightscape   I can confirm that rows are not lost when using 0.13.2.  Same for 0.13.3.  Thanks!
