### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Append mode is not supported by com.crealytics.spark.excel.DefaultSource

### ISSUE THREAD

**Issue by Soham05** [crealytics/spark-excel#236]
This issue was already discussed but opening again as getting the same error 

Trying to write two data frames in single excel file using ("append") mode.
_________________________________________________________________________________________________________
Code used:
      df1.write
           .format("com.crealytics.spark.excel")
           .option("dataAddress", "abc") //write to this sheet
           .option("useHeader", "true")
           .mode("overwrite")
           .save()
    
    df2.write
           .format("com.crealytics.spark.excel")
           .option("dataAddress", "efg") //write to this sheet
           .option("useHeader", "true")
           .mode("overwrite")
           .save()
    

_____________________________________________________________________________________________________
Environment:
Spark 2.0+
Scala: 2.12
spark-excel_2.12-0.13.1.jar

ERROR:
Exception in thread "main" java.lang.RuntimeException: Append mode is not supported by com.crealytics.spark.excel.DefaultSource
        at scala.sys.package$.error(package.scala:27)
        at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:55)
        at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:471)
        at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:50)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:609)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:233)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:217)

**Comment by Soham05** [comment]
Issue was solved as the jar was corrupted. My bad!
