### ISSUE TITLE
NoSuchMethodError: org.apache.spark.sql.execution.datasources.FailureSafeParser.<init>

### ISSUE THREAD

**Issue by yuzhangyi** [crealytics/spark-excel#238]
When I try to read excel data, it meets following error. I have shade "commons-compress", do I need to shade others packages to let databricks (spark cluster) can work it with? @nightscape  could you help give some suggestion and ideas? Thank you very much.

**package reference in SBT**
"com.monitorjbl" % "xlsx-streamer" % "2.1.0" excludeAll (
    ExclusionRule(organization = "org.apache.spark")
 )

**Code:**
file: PartitionedFile => {
      val conf = broadcastedHadoopConf.value.value
      val reader = WorkbookReader(options + ("path" -> file.filePath), conf)
      val dataLocator = DataLocator(options)
      val workbook = reader.openWorkbook
      val allDataIterator = dataLocator.readFrom(workbook).buffered

      val parser = new ExcelParser(dataSchema, requiredSchema, excelOptions)
      val safeParser = new FailureSafeParser[Array[Cell]](
        input => Seq(parser.parse(input)),
        parser.options.parseMode,
        requiredSchema,
        parser.options.columnNameOfCorruptRecord
      )
      val iter = if (excelOptions.firstRowAsHeaderFlag) allDataIterator.drop(1) else allDataIterator
      val rowsIter = iter.flatMap(row => safeParser.parse(row.toArray))

**Error:**
20/04/26 14:06:29 INFO Dataflow AppManager: name=ErrorHandler.formatError, opId=, message=Original message: DF-SYS-0 Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 7, 10.139.64.4, executor 0): com.databricks.sql.io.FileReadException: Error while reading file wasbs:REDACTED_LOCAL_PART@zhanyu2016.blob.core.windows.net/xlsx/releases-2.xlsx.
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1$$anon$2.logFileNameAndThrow(FileScanRDD.scala:331)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1$$anon$2.getNext(FileScanRDD.scala:310)
	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:397)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:250)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:640)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:140)
	at org.apache.spark.scheduler.Task.run(Task.scala:113)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$13.apply(Executor.scala:533)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1541)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:539)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
**Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.FailureSafeParser.<init>**(Lscala/Function1;Lorg/apache/spark/sql/catalyst/util/ParseMode;Lorg/apache/spark/sql/types/StructType;Ljava/lang/String;)V
	at org.apache.spark.sql.execution.datasources.excel.ExcelFileFormat$$anonfun$buildReader$1.apply(ExcelFileFormat.scala:65)
	at org.apache.spark.sql.execution.datasources.excel.ExcelFileFormat$$anonfun$buildReader$1.apply(ExcelFileFormat.scala:57)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(FileFormat.scala:147)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(FileFormat.scala:134)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1$$anon$2.getNext(FileScanRDD.scala:281)

**Comment by nightscape** [comment]
Does the same code work locally?
It looks like the version of `FailureSafeParser` is different than the one you compiled against.
I would recommend to find out which exact version of Spark is running on Databricks and check the Spark sources on Github for that specific version how the exact signature of the `FailureSafeParser.??` method (the method name itself seems to miss here) looks like.

**Comment by yuzhangyi** [comment]
> Does the same code work locally?
> It looks like the version of `FailureSafeParser` is different than the one you compiled against.
> I would recommend to find out which exact version of Spark is running on Databricks and check the Spark sources on Github for that specific version how the exact signatures of the `FailureSafeParser` constructors looks like.

Yes, the issue comes from "FailureSafeParser" while it can work well at local. After rewrite similar logic of "FailureSafeParser", it can work well with spark cluster now. Thanks for your help.
