### ISSUE TITLE
java.io.IOException: GC overhead limit exceeded at shader.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:326) at shadeio.poi.ss.usermodel.WorkbookFactory.createXSSFWorkbook(WorkbookFactory.java:296)

### ISSUE THREAD

**Issue by pankajpkh24** [crealytics/spark-excel#239]
I have written one method which actually loads the Excel and its sheet, so which is working fine in local, But the same I am deploying to Hadoop cluster it is giving me GC overhead memory error :
Note: in my Excel file I have more than 10 sheets and every sheet have 30 rows and  30 columns when I am removing all sheet and keeping one sheet it is working fine?
Any problem, please suggest.

My Code :   Dataset<Row> excelDataSet =
            dataLoaderContext.getSparkSession().read()
                .format("com.crealytics.spark.excel")
                .option("header", "true")
                .option("dataAddress",xlSheetName+"!A")
                .option("useHeader", "true")
                .option("treatEmptyValuesAsNulls", "true")
                .option("inferSchema", "true")
                .option("addColorColumns", "false")
                .load(xlFilePathWithName);

and dependency I have kept is :  
 <dependency>
            <groupId>com.crealytics</groupId>
            <artifactId>spark-excel_2.11</artifactId>
            <version>0.12.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>1.14</version>
        </dependency>

java.io.IOException: GC overhead limit exceeded
        at shadeio.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:326)
        at shadeio.poi.ss.usermodel.WorkbookFactory.createXSSFWorkbook(WorkbookFactory.java:296)
        at shadeio.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:214)
        at shadeio.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:180)
        at com.crealytics.spark.excel.DefaultWorkbookReader$$anonfun$openWorkbook$1.apply(WorkbookReader.scala:42)
        at com.crealytics.spark.excel.DefaultWorkbookReader$$anonfun$openWorkbook$1.apply(WorkbookReader.scala:42)
        at scala.Option.fold(Option.scala:158)
        at com.crealytics.spark.excel.DefaultWorkbookReader.openWorkbook(WorkbookReader.scala:42)
        at com.crealytics.spark.excel.WorkbookReader$class.withWorkbook(WorkbookReader.scala:14)
        at com.crealytics.spark.excel.DefaultWorkbookReader.withWorkbook(WorkbookReader.scala:38)
        at com.crealytics.spark.excel.ExcelRelation.buildScan(ExcelRelation.scala:75)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$12.apply(DataSourceStrategy.scala:295)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$12.apply(DataSourceStrategy.scala:295)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:332)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:331)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProjectRaw(DataSourceStrategy.scala:412)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProject(DataSourceStrategy.scala:327)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy.apply(DataSourceStrategy.scala:291)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:62)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:62)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)

Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.apache.xmlbeans.impl.store.Cur.createElementXobj(Cur.java:260)
        at org.apache.xmlbeans.impl.store.Cur$CurLoadContext.startElement(Cur.java:2997)
        at org.apache.xmlbeans.impl.store.Locale$SaxHandler.startElement(Locale.java:3146)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)

**Comment by nightscape** [comment]
A few suggestions:

- Always use the latest version of this plugin (and check the CHANGELOG and README for changes in the options)
- Give more memory to Spark, this should reduce pressure on the GC
- The `dataAddress` should be `!A1`

**Comment by pankajpkh24** [comment]
> A few suggestions:
> 
> * Always use the latest version of this plugin (and check the CHANGELOG and README for changes in the options)
> * Give more memory to Spark, this should reduce pressure on the GC
> * The `dataAddress` should be `!A1`

HI @nightscape what should be the max memory we can in "maxRowsInMemory" options ?

**Comment by nightscape** [comment]
I would say sane values for `maxRowsInMemory` are a few hundred rows.
Have you tried increasing the memory available to Spark workers and master?

**Comment by pankajpkh24** [comment]
> I would say sane values for `maxRowsInMemory` are a few hundred rows.
> Have you tried increasing the memory available to Spark workers and master?

@nightscape I increase the value like 2g then it worked, but my question is just for 2.4 MB of Excel file why do I need this much memory? any thought?

By the way very thanks for reply @nightscape

**Comment by nightscape** [comment]
Good question. Spark by itself uses a lot of memory already and I haven't really optimized for memory consumption in any way.

**Comment by pankajpkh24** [comment]
> Good question. Spark by itself uses a lot of memory already and I haven't really optimized for memory consumption in any way.

Hmm ... I appreciate your quick response . for now my use case is working.
