### ISSUE TITLE
getting javassist issue because of the dependency

### ISSUE THREAD

**Issue by pankajpkh24** [crealytics/spark-excel#257]
Hi,
I am using spark 2.2
and spark_excel_0.13.1

I am using java 8

then I am getting the issue 

Caused by: java.io.IOException: invalid constant type: 19 at 5
at javassist.bytecode.ConstPool.readOne(ConstPool.java:1236)
at javassist.bytecode.ConstPool.read(ConstPool.java:1167)
at javassist.bytecode.ConstPool.(ConstPool.java:175)
at javassist.bytecode.ClassFile.read(ClassFile.java:777)
at javassist.bytecode.ClassFile.(ClassFile.java:118)
at org.hibernate.ejb.packaging.AbstractJarVisitor.checkAnnotationMatching(AbstractJarVisitor.java:246)
at org.hibernate.ejb.packaging.AbstractJarVisitor.executeJavaElementFilter(AbstractJarVisitor.java:212)
at org.hibernate.ejb.packaging.AbstractJarVisitor.addElement(AbstractJarVisitor.java:173)
at org.hibernate.ejb.packaging.FileZippedJarVisitor.doProcessElements(FileZippedJarVisitor.java:124)
at org.hibernate.ejb.packaging.AbstractJarVisitor.getMatchingEntries(AbstractJarVisitor.java:149)
at org.hibernate.ejb.packaging.NativeScanner.getClassesInJar(NativeScanner.java:128)
... 20 more

**Comment by nightscape** [comment]
Might be some problem related to Java 9:
https://stackoverflow.com/questions/46132019/java-io-ioexception-invalid-constant-type-19-at-5
https://github.com/jboss-javassist/javassist/issues/147

I don't think it's related to spark-excel.
