### ISSUE TITLE
Imports for classes in pfanning poi-shared-strings shaded but classes not included in jar

### ISSUE THREAD

**Issue by syndic8-stephen** [crealytics/spark-excel#258]
This error in latest snapshot 0.13.3+3-d1c04e7c-SNAPSHOT  I came across this as I had the issue #181 and so checked with the snapshot as the release is not yet available on maven.  

## Expected Behavior
No  NoClassDefFoundError when parsing.

## Current Behavior
Exception when reading Xslx as below.  Calling class is shaded in excel-streaming-reader.   Imports In StreamingReader show reference to shadeio/pjfanning/poi/xssf/streaming/TempFileSharedStringsTable  that is not in shaded location in jar.

`

java.lang.NoClassDefFoundError: shadeio/pjfanning/poi/xssf/streaming/TempFileSharedStringsTable

	at shadeio.pjfanning.xlsx.StreamingReader.builder(StreamingReader.java:88)
	at com.crealytics.spark.excel.StreamingWorkbookReader.openWorkbook(WorkbookReader.scala:59)
	at com.crealytics.spark.excel.WorkbookReader.withWorkbook(WorkbookReader.scala:14)
	at com.crealytics.spark.excel.WorkbookReader.withWorkbook$(WorkbookReader.scala:13)
	at com.crealytics.spark.excel.StreamingWorkbookReader.withWorkbook(WorkbookReader.scala:55)
	at com.crealytics.spark.excel.ExcelRelation.excerpt$lzycompute(ExcelRelation.scala:30)
	at com.crealytics.spark.excel.ExcelRelation.excerpt(ExcelRelation.scala:30)
	at com.crealytics.spark.excel.ExcelRelation.headerColumns$lzycompute(ExcelRelation.scala:104)
	at com.crealytics.spark.excel.ExcelRelation.headerColumns(ExcelRelation.scala:103)
	at com.crealytics.spark.excel.ExcelRelation.$anonfun$inferSchema$1(ExcelRelation.scala:169)
	at scala.Option.getOrElse(Option.scala:189)
	at com.crealytics.spark.excel.ExcelRelation.inferSchema(ExcelRelation.scala:168)
	at com.crealytics.spark.excel.ExcelRelation.<init>(ExcelRelation.scala:34)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:40)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:339)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:240)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:229)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:229)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:190)`

Shaded imports in StreamingReader class

`import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;
import shadeio.pjfanning.poi.xssf.streaming.TempFileSharedStringsTable;
import shadeio.pjfanning.xlsx.exceptions.MissingSheetException;
import shadeio.pjfanning.xlsx.exceptions.OpenException;
import shadeio.pjfanning.xlsx.exceptions.ParseException;`

## Possible Solution
Need to include poi-shared-strings in shadedDeps  or be more specific with the shared renames com.github.pjfanning.** so it does not pick up classes in this jar and leave it as a third party.

## Steps to Reproduce (for bugs)
 I am afraid for commercial reasons I cannot upload the actual file.  If needed I can see if I can recreate it with anonymized data.
1.
    `
    Dataset<Row> df1 = spark.read().format("com.crealytics.spark.excel")
            .option("useHeader", "true")
            .option("header","true")
            .option("inferSchema", "false")
            .option("maxRowsInMemory", 20)
            .load("/path/file.xlsx");
    `
I am using 
    org.apache.spark:spark-core_2.12:3.0.0-preview2

**Comment by nightscape** [comment]
Hey @syndic8-stephen, thanks for the detailed report!
Looks like you are familiar with shading, would you mind giving this a try and create a PR?

**Comment by syndic8-stephen** [comment]
> Hey @syndic8-stephen, thanks for the detailed report!
> Looks like you are familiar with shading, would you mind giving this a try and create a PR?

I will give it a go.  I am new to Scala coming from Java but got the code down and made the change.  I will test and create a PR if it works.

**Comment by syndic8-stephen** [comment]
I have created a pull request for this https://github.com/crealytics/spark-excel/pull/261
