### ISSUE TITLE
cannot create a working fat jar

### ISSUE THREAD

**Issue by parisni** [crealytics/spark-excel#297]
hi

Up to now, I am loading the spark-excel library with `--packages` from spark-submit. This is working fine.

However I d'like to load the library from `--jars` and get the stuff locally instead of pulling from a remote server.

I did `sbt assembly` and pass the resulting fat jar to `--jars`. 

However, when running the code (which is actually working with `--packages`) I get the bellow error:

```scala
spark.read.format("com.crealytics.spark.excel").option("header","true").load("file:///home/test.xlsx").show
java.io.IOException: org/apache/commons/collections4/IteratorUtils
  at shadeio.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:351)
  at shadeio.poi.ss.usermodel.WorkbookFactory.createXSSFWorkbook(WorkbookFactory.java:314)
  at shadeio.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:232)
  at shadeio.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:198)
  at com.crealytics.spark.excel.DefaultWorkbookReader$$anonfun$openWorkbook$1.apply(WorkbookReader.scala:50)
  at com.crealytics.spark.excel.DefaultWorkbookReader$$anonfun$openWorkbook$1.apply(WorkbookReader.scala:50)
  at scala.Option.fold(Option.scala:158)
  at com.crealytics.spark.excel.DefaultWorkbookReader.openWorkbook(WorkbookReader.scala:50)
  at com.crealytics.spark.excel.WorkbookReader$class.withWorkbook(WorkbookReader.scala:14)
  at com.crealytics.spark.excel.DefaultWorkbookReader.withWorkbook(WorkbookReader.scala:46)
  at com.crealytics.spark.excel.ExcelRelation.excerpt$lzycompute(ExcelRelation.scala:30)
  at com.crealytics.spark.excel.ExcelRelation.excerpt(ExcelRelation.scala:30)
  at com.crealytics.spark.excel.ExcelRelation.headerColumns$lzycompute(ExcelRelation.scala:104)
  at com.crealytics.spark.excel.ExcelRelation.headerColumns(ExcelRelation.scala:103)
  at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:168)
  at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:167)
  at scala.Option.getOrElse(Option.scala:121)
  at com.crealytics.spark.excel.ExcelRelation.inferSchema(ExcelRelation.scala:167)
  at com.crealytics.spark.excel.ExcelRelation.<init>(ExcelRelation.scala:34)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:40)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
  ... 49 elided
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections4/IteratorUtils
  at shadeio.poi.openxml4j.util.ZipInputStreamZipEntrySource.getEntries(ZipInputStreamZipEntrySource.java:61)
  at shadeio.poi.openxml4j.opc.ZipPackage.getPartsImpl(ZipPackage.java:288)
  at shadeio.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:726)
  at shadeio.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:304)
  at shadeio.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:134)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at shadeio.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:339)
  ... 74 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections4.IteratorUtils
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 84 more
```

Any way to properly build a fat jar ? 
thanks

**Comment by parisni** [comment]
well I work around by also adding those jars:

```
com.crealytics_spark-excel_2.11-0.13.1.jar 
org.apache.commons_commons-collections4-4.3.jar
org.apache.poi_poi-ooxml-schemas-4.1.0.jar 
org.apache.xmlbeans_xmlbeans-3.1.0.jar 
```
would be great if the fat jar would also contain them

**Comment by nightscape** [comment]
I've tried to keep the JAR size a smaller by only adding things to the Fat JAR that conflict with Spark's bundled libraries.
I guess that for other Spark plugins it would be similar: If you switch from `--packages` to `--jars` you have to take care of adding all required dependencies manually.
If there are good reasons to change the approach I'm happy to rethink.

**Comment by quanghgx** [comment]
Hi @parisni 
1+ with Martin comment and your solution seem the best we can get to. Also added that to the [wiki](https://github.com/crealytics/spark-excel/wiki) page.
Going to resolve this ticket.
