### ISSUE TITLE
Dataframe write gives error in createRelation method

### ISSUE THREAD

**Issue by BVSKanth** [crealytics/spark-excel#34]
Hi,
I am trying to write dataframe to a file and getting following exception.

java.lang.AbstractMethodError: com.crealytics.spark.excel.DefaultSource.createRelation(Lorg/apache/spark/sql/SQLContext;Lorg/apache/spark/sql/SaveMode;Lscala/collection/immutable/Map;Lorg/apache/spark/sql/DataFrame;)Lorg/apache/spark/sql/sources/BaseRelation;
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
        at org.apache.spark.sql.DataFrameWriter.dataSource$lzycompute$1(DataFrameWriter.scala:181)
        at org.apache.spark.sql.DataFrameWriter.org$apache$spark$sql$DataFrameWriter$$dataSource$1(DataFrameWriter.scala:181)
        at org.apache.spark.sql.DataFrameWriter$$anonfun$save$1.apply$mcV$sp(DataFrameWriter.scala:188)
        at org.apache.spark.sql.DataFrameWriter.executeAndCallQEListener(DataFrameWriter.scala:154)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:188)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:172)
     

Thanks,
Srikanth

**Comment by nightscape** [comment]
Which Spark version are you using? Sounds like a version incompatibility.

**Comment by BVSKanth** [comment]
Hi, 
I am using Spark 1.6.

Thanks,
Srikanth

**Comment by nightscape** [comment]
Spark < 2.0 is actually not tested and your example seems to indicate that it's actually not working anymore.
I'll update the README accordingly.
Are you able to update to Spark >= 2.0?
We're using Spark >= 2.0, so we won't invest time in maintaining older versions.
If you absolutely need that, you'd need to create a PR with the required changes.
