### ISSUE TITLE
0.8.3 Version - Parameter "location" is missing in options

### ISSUE THREAD

**Issue by BVSKanth** [crealytics/spark-excel#37]
Hi,
I am using Spark-Excel 0.8.3 version with Spark 1.6 and Scala 2.10 and getting this exception

Exception in thread "main" java.lang.IllegalArgumentException: Parameter "location" is missing in options.
	at com.crealytics.spark.excel.DefaultSource.checkParameter(DefaultSource.scala:37)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:17)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:7)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:109)
	at sparkExcelClass$delayedInit$body.apply(sparkExcelClass.scala:28)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at sparkExcelClass$.main(sparkExcelClass.scala:4)
	at sparkExcelClass.main(sparkExcelClass.scala)

Thanks,
Srikanth

**Comment by nightscape** [comment]
You seem to be using the code from the old example in the README.
Please upgrade Spark to >= 2.0, spark-excel to 0.9.6 and use the new example code from the README:
https://github.com/crealytics/spark-excel#create-a-dataframe-from-an-excel-file
