### ISSUE TITLE
Issues with DataProc

### ISSUE THREAD

**Issue by AlbertUlysses** [crealytics/spark-excel#393]
## Expected Behavior
When trying to read the library into a PySpark Notebook in Dataproc, I get the infamous: 
`Py4JJavaError: An error occurred while calling o571.load.
: java.lang.ClassNotFoundException: Failed to find data source: com.crealytics.spark.excel. Please find packages at http://spark.apache.org/third-party-projects.html`
I am reading the most current version: "com.crealytics:spark-excel_2.12:0.13.7"

## Current Behavior
Currently I am getting an error that says the library cannot be found.
stack trace:
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-133-b0dd8da5e616> in <module>
----> 1 df = spark.read.format("com.crealytics.spark.excel") \
      2     .option("useHeader", "true") \
      3     .option("inferSchema", "true") \
      4     .load("gs://completeledger/rawexcel/Complete Ledger.xlsx")

/usr/lib/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    202         self.options(**options)
    203         if isinstance(path, str):
--> 204             return self._df(self._jreader.load(path))
    205         elif path is not None:
    206             if type(path) != list:

/usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/usr/lib/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    109     def deco(*a, **kw):
    110         try:
--> 111             return f(*a, **kw)
    112         except py4j.protocol.Py4JJavaError as e:
    113             converted = convert_exception(e.java_exception)

/usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o571.load.
: java.lang.ClassNotFoundException: Failed to find data source: com.crealytics.spark.excel. Please find packages at http://spark.apache.org/third-party-projects.html
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:689)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:743)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:266)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:240)
	at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.crealytics.spark.excel.DefaultSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$5(DataSource.scala:663)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$4(DataSource.scala:663)
	at scala.util.Failure.orElse(Try.scala:224)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:663)
	... 13 more
```

## Possible Solution
Not sure if the way I'm reading it in is wrong or if it has something to do with using Dataproc

## Steps to Reproduce (for bugs)
Here is the code I used:
To read and start session:
```
spark = SparkSession.builder \
    .appName("ledger") \
    .config("spark.jars.packages","com.crealytics:spark-excel_2.12:0.13.7") \
    .getOrCreate()

spark
```
This is the Spark Session Information:
```


SparkSession - hive

SparkContext

Spark UI

Version
    v3.1.1
Master
    yarn
AppName
    PySparkShell

```
Then the code where the error occurs:
```
df = spark.read.format("com.crealytics.spark.excel") \
    .option("useHeader", "true") \
    .option("inferSchema", "true") \
    .load("gs://completeledger/rawexcel/XXXX.xlsx")
```
Followed by the stack trace posted above.

## Context
> How has this issue affected you? What are you trying to accomplish?
> Providing context helps us come up with a solution that is most useful in the real world

## Your Environment
> Include as many relevant details about the environment you experienced the bug in
* Spark version 3.1 with Pyspark
* Spark-Excel version: not sure but it's an xlsx file so it's newer
* Operating System and version, cluster environment, ...: ubuntu18 on Dataproc

**Comment by nightscape** [comment]
Hi @AlbertUlysses, I haven't worked with DataProc yet.
What happens if you try to use another non-bundled package with the same approach?
E.g.
* https://github.com/saurfang/spark-sas7bdat
* https://github.com/sadikovi/spark-netflow
* https://github.com/neo4j-contrib/neo4j-spark-connector

**Comment by AlbertUlysses** [comment]
Hi, @nightscape 
I figured out the issue, and I was able to correct it.
PySpark kernels (PySpark notebooks) cannot change their classpath in runtime; therefore, it means they cannot use any external jars at runtime. The solution is to use a Python Notebook instead.
