### ISSUE TITLE
NullPointerException when the first row of a sheet has only empty fields.

### ISSUE THREAD

**Issue by virtualramblas** [crealytics/spark-excel#4]
Hi everybody. I found the following issue using the release 0.8.2 of the library for Scala 2.11 (and Spark 1.6.2): when the selected sheet to transform to DataFrame has the first row containing only empty fields it throws a NullPointerException:  

_17/03/21 23:03:49 INFO BlockManagerMaster: Registered BlockManager
Exception in thread "main" java.lang.NullPointerException
	at com.crealytics.spark.excel.ExcelRelation.<init>(ExcelRelation.scala:30)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:31)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:7)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
	at com.optum.sparkexcelpoc.DataFrameFromExcel$.main(DataFrameFromExcel.scala:30)
	at com.optum.sparkexcelpoc.DataFrameFromExcel.main(DataFrameFromExcel.scala)_

Browsing the source code I found the root cause of the problem and how to fix it. Please let me know if you're happy to have me fixing it and what procedure do you follow to accept changes. Thanks a lot.

**Comment by nightscape** [comment]
A PR would be great!
As the project currently doesn't have any tests, we don't have any specific procedures for accepting changes.
I'll just do a quick code review.

**Comment by virtualramblas** [comment]
Hi Martin,

Thanks a lot for the reply. Going to do a PR as soon as the code is ready and tested. Thanks a lot.

Best Regards,
Guglielmo

**Comment by virtualramblas** [comment]
This issue has been solved through commit 8427d1e
