### ISSUE TITLE
An error is reported when the excel header is a number

### ISSUE THREAD

**Issue by wushuaidegit** [crealytics/spark-excel#435]
scala version:2.11
spark-excel version:0.12.5
[](url)
Cannot get a STRING value from a NUMERIC cell
java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC cell
	at shadeio.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:1003)
	at shadeio.poi.xssf.usermodel.XSSFCell.getRichStringCellValue(XSSFCell.java:389)
	at shadeio.poi.xssf.usermodel.XSSFCell.getStringCellValue(XSSFCell.java:341)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7.com$crealytics$spark$excel$ExcelRelation$$anonfun$$colName$1(ExcelRelation.scala:119)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7$$anonfun$12.apply(ExcelRelation.scala:122)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7$$anonfun$12.apply(ExcelRelation.scala:122)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7.apply(ExcelRelation.scala:122)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7.apply(ExcelRelation.scala:105)
	at scala.Option.getOrElse(Option.scala:121)
	at com.crealytics.spark.excel.ExcelRelation.headerColumns$lzycompute(ExcelRelation.scala:105)
	at com.crealytics.spark.excel.ExcelRelation.headerColumns(ExcelRelation.scala:104)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:162)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:161)
	at scala.Option.getOrElse(Option.scala:121)
	at com.crealytics.spark.excel.ExcelRelation.inferSchema(ExcelRelation.scala:161)
	at com.crealytics.spark.excel.ExcelRelation.<init>(ExcelRelation.scala:35)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:40)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)

![image](https://user-images.githubusercontent.com/75476316/137442050-bfce354e-58d6-48c1-8095-58ce83f4a751.png)

**Comment by wushuaidegit** [comment]
this picture is shadeio.poi.xssf.usermodel.XSSFCell.Class

**Comment by quanghgx** [comment]
Going to close this ticket. Please reopen it when we have more input to investigate.
Sincerely,
