### ISSUE TITLE
Unable to access container xxx in account yyy.blob.core.windows.net using anonymous credentials

### ISSUE THREAD

**Issue by ghost** [crealytics/spark-excel#437]
I am using Azure Databricks and I am trying to read an Excel file (xlsx) from a Storage account (ADLS Gen2). I have the accountKey setup in the cluster config. In the storage account I have a folder and in it two files: Budgte.csv and Budget.xlsx. All three are valid files and I can just open them on my machine. I execute this python code

`ldaFullPath = "wasbs://containerName@AccountName.blob.core.windows.net/FolderName/"

df = spark.read \
  .format("csv") \
  .option("header", "true") \
  .option("delimiter", ";") \
  .load(ldaFullPath+"Budget.csv")

df = spark.read \
  .format("com.crealytics.spark.excel") \
  .option("header", "true") \
  .option("inferSchema", "true") \
  .load(ldaFullPath+"Budget.xlsx")`

The first command succeeds and I get the headers from the file. A df.show() will show me the content. The second command fails with this error: 
shaded.databricks.org.apache.hadoop.fs.azure.AzureException: shaded.databricks.org.apache.hadoop.fs.azure.AzureException: Unable to access container containerName in account AccountName.blob.core.windows.net using anonymous credentials, and no credentials found for them  in the configuration.

I am using Databricks runtime 8.3 with Apache Spark 3.1.1 and Scala 2.12. What I have tried so far (all with the same error):
- Different version of the crealytics library. I tries 14.0, 13.7 and 13.6. All of them for scala 2.12
- The above code is in Python; I also tried it in scala
- Use an xls file instead of an xlsx
- Use different sheet names. The file has just one sheet named 'Sheet1'
- Set the accountKey in the notebook (instead of the cluster config) like this: spark.conf.set("fs.azure.account.key.AccountName.dfs.core.windows.net", accountKey)

In the end I mounted the path to a new mountPoint and now I dont have this issue anymore. However, if I do that I get a different issue which I will post separately to keep the thread clean.

This this the full stack trace. Any help is very much appreciated!

`---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-3117361117344004> in <module>
     10 
     11 #Load data into a DataFrame and repartition to 1 for better performance
---> 12 df = spark.read \
     13   .format("com.crealytics.spark.excel") \
     14   .option("header", "true") \

/databricks/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    202         self.options(**options)
    203         if isinstance(path, str):
--> 204             return self._df(self._jreader.load(path))
    205         elif path is not None:
    206             if type(path) != list:

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115     def deco(*a, **kw):
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:
    119             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o387.load.
: shaded.databricks.org.apache.hadoop.fs.azure.AzureException: shaded.databricks.org.apache.hadoop.fs.azure.AzureException: Unable to access container containerName  in account AccountName.blob.core.windows.net using anonymous credentials, and no credentials found for them  in the configuration.
	at shaded.databricks.org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.createAzureStorageSession(AzureNativeFileSystemStore.java:1045)
	at shaded.databricks.org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.initialize(AzureNativeFileSystemStore.java:499)
	at shaded.databricks.org.apache.hadoop.fs.azure.NativeAzureFileSystem.initialize(NativeAzureFileSystem.java:1360)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
	at com.crealytics.spark.excel.WorkbookReader$.readFromHadoop$1(WorkbookReader.scala:35)
	at com.crealytics.spark.excel.WorkbookReader$.$anonfun$apply$2(WorkbookReader.scala:41)
	at com.crealytics.spark.excel.DefaultWorkbookReader.$anonfun$openWorkbook$1(WorkbookReader.scala:49)
	at scala.Option.fold(Option.scala:251)
	at com.crealytics.spark.excel.DefaultWorkbookReader.openWorkbook(WorkbookReader.scala:49)
	at com.crealytics.spark.excel.WorkbookReader.withWorkbook(WorkbookReader.scala:14)
	at com.crealytics.spark.excel.WorkbookReader.withWorkbook$(WorkbookReader.scala:13)
	at com.crealytics.spark.excel.DefaultWorkbookReader.withWorkbook(WorkbookReader.scala:45)
	at com.crealytics.spark.excel.ExcelRelation.excerpt$lzycompute(ExcelRelation.scala:31)
	at com.crealytics.spark.excel.ExcelRelation.excerpt(ExcelRelation.scala:31)
	at com.crealytics.spark.excel.ExcelRelation.headerColumns$lzycompute(ExcelRelation.scala:102)
	at com.crealytics.spark.excel.ExcelRelation.headerColumns(ExcelRelation.scala:101)
	at com.crealytics.spark.excel.ExcelRelation.$anonfun$inferSchema$1(ExcelRelation.scala:163)
	at scala.Option.getOrElse(Option.scala:189)
	at com.crealytics.spark.excel.ExcelRelation.inferSchema(ExcelRelation.scala:162)
	at com.crealytics.spark.excel.ExcelRelation.<init>(ExcelRelation.scala:35)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:35)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:13)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:8)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:390)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:432)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:399)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:399)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
Caused by: shaded.databricks.org.apache.hadoop.fs.azure.AzureException: Unable to access container containerName  in account AccountName.blob.core.windows.net using anonymous credentials, and no credentials found for them  in the configuration.
	at shaded.databricks.org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.connectUsingAnonymousCredentials(AzureNativeFileSystemStore.java:804)
	at shaded.databricks.org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.createAzureStorageSession(AzureNativeFileSystemStore.java:1040)
	... 40 more
Caused by: hadoop_azure_shaded.com.microsoft.azure.storage.StorageException: Public access is not permitted on this storage account.
	at hadoop_azure_shaded.com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
	at hadoop_azure_shaded.com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
	at hadoop_azure_shaded.com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:196)
	at hadoop_azure_shaded.com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:744)
	at hadoop_azure_shaded.com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:731)
	at shaded.databricks.org.apache.hadoop.fs.azure.StorageInterfaceImpl$CloudBlobContainerWrapperImpl.exists(StorageInterfaceImpl.java:243)
	at shaded.databricks.org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.connectUsingAnonymousCredentials(AzureNativeFileSystemStore.java:797)
	... 41 more`

**Comment by vineethReddy-JLL** [comment]
Any updates on this? Facing similar issue.

**Comment by nightscape** [comment]
Sorry, that one slipped my attention the first time...
You could try using `.format("excel")` instead of `.format("com.crealytics.spark.excel")`.
That uses the newer v2 implementation which works a little differently.
