### ISSUE TITLE
Writing to Excel using v2/excel format: Table does not support overwrite by expression

### ISSUE THREAD

**Issue by christianknoepfle** [crealytics/spark-excel#539]
## Description
When writing a dataframe to excel in overwrite mode I would expect that a file will be created in the given path. 

Following code snippet 

        dfCsv.write
               .format("excel")
                .option("path", targetDir)
                .option("header", true)
                .mode(SaveMode.Overwrite)
                .save()

fails with the exception

```
[info]   org.apache.spark.SparkException: Table does not support overwrite by expression: ExcelTable(excel file:/C:/DATA/Dev/git/spark-excel-test/tmp/v2,org.apache.spark.sql.SparkSession@305a40b2,org.apache.spark.sql.util.CaseInsensitiveStringMap@b7029722,List(tmp\v2),None)  
[info]   at org.apache.spark.sql.execution.datasources.v2.OverwriteByExpressionExec.run(WriteToDataSourceV2Exec.scala:292)
...
```

Doing the same with the V1 API (and the path option points to a dedicated file), it works as expected

    dfCsv.write
        .format("com.crealytics.spark.excel")
        .option("path", targetFile)
        .option("header", true)
        .mode(SaveMode.Overwrite)
        .save()

## Steps to Reproduce (for bugs)
I published a repo with the most basic setup (just spark, spark-excel and scalatest) and a few tests that demonstrate the issue

    https://github.com/christianknoepfle/spark-excel-test

Just pull it and then run sbt test to reproduce the issue (it contains simple read/write test for v1/v2 api)

## Context
We want the V2 API because of two reason:
- *path-option* just points to a path and not an individual file. So same behavior as the other file formats bundled with spark
- need *partitionBy* functionality

## Your Environment
We use Spark 3.0.3, Scala, 0.16.0 spark-excel, Windows (but also Linux on AWS EMR)

### Full trace:
```
[info]   org.apache.spark.SparkException: Table does not support overwrite by expression: ExcelTable(excel file:/C:/DATA/Dev/git/spark-excel-test/tmp/v2,org.apache.spark.sql.SparkSession@305a40b2,org.apache.spark.sql.util.CaseInsensitiveStringMap@b7029722,List(tmp\v2),None)  
[info]   at org.apache.spark.sql.execution.datasources.v2.OverwriteByExpressionExec.run(WriteToDataSourceV2Exec.scala:292)
[info]   at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:39)
[info]   at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:39)
[info]   at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.doExecute(V2CommandExec.scala:54)
[info]   at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
[info]   at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
[info]   at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[info]   at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
[info]   at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
[info]   at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:127)
[info]   ...
```

**Comment by christianknoepfle** [comment]
I could simply fix the issue by replacing the SaveMode.Overwrite by SaveMode.Append.  So Overwrite Mode doesn't work as expected. 

For the Append mode: When I simply double the dfCsv.save() command to see if append creates multiple excel, I ran into another issue:   

Your InputStream was neither an OLE2 stream, nor an OOXML stream or you haven't provide the poi-ooxml*.jar in the classpath/modulepath - FileMagic: OOXML, having providers: []
java.io.IOException: Your InputStream was neither an OLE2 stream, nor an OOXML stream or you haven't provide the poi-ooxml*.jar in the classpath/modulepath - FileMagic: OOXML, having providers: []
	at shadeio.poi.ss.usermodel.WorkbookFactory.wp(WorkbookFactory.java:309)
	at shadeio.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:208)
	at shadeio.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:172)
	at com.crealytics.spark.v2.excel.ExcelHelper.getWorkbook(ExcelHelper.scala:107)
	at com.crealytics.spark.v2.excel.ExcelHelper.getRows(ExcelHelper.scala:122)
	at com.crealytics.spark.v2.excel.ExcelTable.infer(ExcelTable.scala:69)
	at com.crealytics.spark.v2.excel.ExcelTable.inferSchema(ExcelTable.scala:42)
	at org.apache.spark.sql.execution.datasources.v2.FileTable.$anonfun$dataSchema$4(FileTable.scala:69)
	at scala.Option.orElse(Option.scala:447)
	at org.apache.spark.sql.execution.datasources.v2.FileTable.dataSchema$lzycompute(FileTable.scala:69)
	at org.apache.spark.sql.execution.datasources.v2.FileTable.dataSchema(FileTable.scala:63)
	at org.apache.spark.sql.execution.datasources.v2.FileTable.schema$lzycompute(FileTable.scala:82)
	at org.apache.spark.sql.execution.datasources.v2.FileTable.schema(FileTable.scala:80)
	at com.crealytics.spark.v2.excel.ExcelDataSource.inferSchema(ExcelDataSource.scala:85)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:81)
	at org.apache.spark.sql.DataFrameWriter.getTable$1(DataFrameWriter.scala:322)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:338)
	at ExcelReadWriteTest.$anonfun$new$8(ExcelReadWriteTest.scala:114)

**Comment by christianknoepfle** [comment]
Thanks, great news. But I couldn't see a new artefact on maven for 0.16.2. I guess the "let's hope" part of you answer didn't work out as hoped ;) :)

**Comment by nightscape** [comment]
Unfortunately, the build failed again...
Do you have any experience with SBT and PGP by any chance? 😃

**Comment by christianknoepfle** [comment]
would be glad to help, but unfortunately no experience with that. Is that around uploading the artifacts to maven where you need the pgp?

**Comment by nightscape** [comment]
Could you try the latest prerelease as well?

**Comment by christianknoepfle** [comment]
just tried 0.16.5-pre1 and it shows the same behaviour.

**Comment by cristichircu** [comment]
Hello!

I just ran into the write issue as well. I tried it with spark-excel 0.16.4 and spark 3.1.1 and I **didn't** run into this issue: "Your InputStream was neither an OLE2 stream, nor an OOXML stream or you haven't provide the poi-ooxml*.jar in the classpath/modulepath - FileMagic: OOXML, having providers: []"

I was able to write in append mode but overwrite mode gives the same error that @christianknoepfle opened this ticket for.

Another issue I found is: if the full path doesn't already exist you receive the follosing error:
`org.apache.spark.sql.AnalysisException: Path does not exist: file:/some/test/path/
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4(DataSource.scala:803)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4$adapted(DataSource.scala:800)
	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:372)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
`

**Comment by christianknoepfle** [comment]
Having the path created automatically would be very nice - it would also work the same way as creating csv files (the path gets created if not existant, just tested that)
The OOXML error appeared when when I write the same dataframe  with append into the same directory. So just
```
dfCsv.write.format("excel").option("path",targetDir).option("header",true).mode(SaveMode.Append).save()
dfCsv.write.format("excel").option("path",targetDir).option("header",true).mode(SaveMode.Append).save()
````
JUst wanted to see if it does append....

**Comment by cristichircu** [comment]
Sorry, but I wasn't able to reproduce that. Append seems to be working fine for me with the latest version even if I double the write command. Considering v2 seems to just write another set of files I'm not sure why calling this multiple times would make a difference.
Btw, I'm using spark from Java, if that makes any difference.

**Comment by quanghgx** [comment]
1+ with @cristichircu , calling .write multiple times might just write another set of files (with uid and part number). Of course, this might not be the intended behavior, reading back will be fine as well, I think.

To be honest, 'overwrite by expression' issue with SaveMode.Overwrite is a known issue. It's more on that I haven't have time to fully understand this mode when adding writing feature (not intended to have writing at first for v2 implementation)
