### ISSUE TITLE
Writing Excel with partitionBy: requirement failed: The provided partitioning does not match of the table.

### ISSUE THREAD

**Issue by christianknoepfle** [crealytics/spark-excel#547]
## Expected Behavior
When I do a 
```
        dfCsv.write
          .partitionBy("col1")
          .format("excel")
          .option("path", targetDir)
          .option("header", true)
          .mode(writeMode)
          .save()
```
I expect to get files that are located in different subdirectories (similar to csv or parquet).
 
## Current Behavior
The mentioned call results in the following exception and no files are written
```
requirement failed: The provided partitioning does not match of the table.
 - provided: col1
 - table: 
java.lang.IllegalArgumentException: requirement failed: The provided partitioning does not match of the table.
 - provided: col1
 - table: 
	at scala.Predef$.require(Predef.scala:281)
	at org.apache.spark.sql.DataFrameWriter.checkPartitioningMatchesV2Table(DataFrameWriter.scala:748)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:350)

```
The exception is not related to the SaveMode (fails with Append and Overwrite)

## Steps to Reproduce (for bugs)

The test code is here:

     https://github.com/christianknoepfle/spark-excel-test

Just clone/download and run the scalatest

## Your Environment
Spark 3.0.3, spark excel 0.16.4

**Comment by christianknoepfle** [comment]
fixed via #562
