### ISSUE TITLE
RuntimeException: Error while encoding: java.lang.RuntimeException: scala.Some is not a valid external type for schema of string

### ISSUE THREAD

**Issue by arnabdasgupta04** [crealytics/spark-excel#584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to read an Excel file in Databricks using the spark-excel library in scala language. It appears that the returned data is wrapped in scala.Some type.

Here is how I invoke the library:

val df_xlsx = spark.read.format("com.crealytics.spark.excel").option("header","true").load("dbfs:/FileStore/demo/Test_file.xlsm")

I am getting the below error while running.

RuntimeException: Error while encoding: java.lang.RuntimeException: scala.Some is not a valid external type for schema of string
Caused by: RuntimeException: scala.Some is not a valid external type for schema of string
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 4 times, most recent failure: Lost task 0.3 in stage 4.0 (TID 16) (10.169.128.132 executor 0): java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: scala.Some is not a valid external type for schema of string
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 0, How to use this form…), StringType), true, false) AS How to use this form…#496
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 1, Troubleshooting), StringType), true, false) AS Troubleshooting#497
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:239)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:210)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:757)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:80)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:178)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:150)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:119)

Please look into it and suggest me about the next step urgently

### Environment

```markdown
- Spark version:3.1.1
- Spark-Excel version:2.12:0.13.1
- OS:
- Cluster environment
```

**Comment by nightscape** [comment]
Please try the newest version before posting bugs.

**Comment by arnabdasgupta04** [comment]
I am using the latest version which is com.crealytics:spark-excel_2.12:3.2.1_0.17.0 . I am getting the below error while using workbook reader .Please advice urgently.

Please find the below image as reference.

![image](https://user-images.githubusercontent.com/63199431/165502213-f48fc26c-9334-420a-8c22-a26633e08c7b.png)

**Comment by nightscape** [comment]
It looks like you're running this in PySpark, right? These instructions are for Scala and won't work in Python.

**Comment by arnabdasgupta04** [comment]
I am using scala , please find the below snapshot for reference .
I am using the latest version which is com.crealytics:spark-excel_2.12:3.2.1_0.17.0 . I am getting the below error while using workbook reader .Please advice urgently.

![image](https://user-images.githubusercontent.com/63199431/165518746-6db34bcc-84d0-47de-9b81-11300bf0f417.png)

**Comment by nightscape** [comment]
I just added the required `import` to `README.md`:
https://github.com/crealytics/spark-excel/commit/935a9494a2dbe15f181b6c55f0efaaf43773e2b4

**Comment by arnabdasgupta04** [comment]
I am reading the sheet name as shown in the above snapshot,  how to store the data from each sheet to the respective dataframe names , I have looped the above output in a scala variable .

**Comment by arnabdasgupta04** [comment]
I am again not able to load xlsx file using the latest version which is com.crealytics:spark-excel_2.12:3.2.1_0.17.0 . 
Please find the below snapshot for your reference .
Please look into it urgently .
![image](https://user-images.githubusercontent.com/63199431/165724573-e84a886d-689f-410c-9262-27aaaa56840d.png)

**Comment by nightscape** [comment]
@arnabdasgupta04 this is a different issue from the original one. Could you please create a new issue and make sure to fill out the form with all required information?

**Comment by krhemanth** [comment]
hey @nightscape  I am getting the same error, while trying to show or filter the dataframe while loading cassandra table via spark scala

 ```code
import org.apache.spark.sql.types.{StringType, IntegerType, LongType, TimestampType, StructField, StructType}
import org.apache.spark.sql.{Row, SparkSession}
import org.apache.spark.sql.cassandra._
import org.apache.spark.sql.functions._

  object init{

    def main(args: Array[String]): Unit = {

      val spark: SparkSession = SparkSession
        .builder()
        .master("local[*]")
        .config("spark.cassandra.connection.host", "localhost")
        .appName("SparkCassandra")
        .getOrCreate()

      //Read Cassandra data using DataFrame
      import spark.implicits._
      import scala.collection.JavaConversions._
      var df = spark.read
        .format("org.apache.spark.sql.cassandra")
        .options(Map( "table" -> "manifest", "keyspace" -> "pelton"))
        .load()
      println("Schema of all manifest logs are below")
      df.printSchema()
      println("Count of records in Manifest table: "+ df.count())
      println("Details of manifest logs are below")
      df.show() 

OutPut

Schema of all manifest logs are below
root
 |-- topic: string (nullable = false)
 |-- partition: string (nullable = false)
 |-- source: string (nullable = false)
 |-- batchid: timestamp (nullable = false)
 |-- endtime: timestamp (nullable = true)
 |-- erredcount: long (nullable = true)
 |-- feedtype: string (nullable = true)
 |-- insertts: timestamp (nullable = true)
 |-- processedcount: long (nullable = true)
 |-- recordcount: long (nullable = true)
 |-- skippedcount: long (nullable = true)
 |-- startime: timestamp (nullable = true)
 |-- status: string (nullable = true)
 |-- updatets: timestamp (nullable = true)

Count of records in Manifest table: 2
Details of manifest logs are below

java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: org.apache.spark.unsafe.types.UTF8String is not a valid external type for schema of string
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 0, skippedcount), LongType) AS skippedcount#89L
staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, TimestampType, fromJavaTimestamp, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 1, batchid), TimestampType), true, false) AS batchid#90
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 2, erredcount), LongType) AS erredcount#91L
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 3, processedcount), LongType) AS processedcount#92L
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, TimestampType, fromJavaTimestamp, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 4, updatets), TimestampType), true, false) AS updatets#93
staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 5, source), StringType), true, false) AS source#94
staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 6, partition), StringType), true, false) AS partition#95
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, TimestampType, fromJavaTimestamp, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 7, startime), TimestampType), true, false) AS startime#96
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 8, recordcount), LongType) AS recordcount#97L
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 9, status), StringType), true, false) AS status#98
staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 10, topic), StringType), true, false) AS topic#99
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, TimestampType, fromJavaTimestamp, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 11, insertts), TimestampType), true, false) AS insertts#100
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 12, feedtype), StringType), true, false) AS feedtype#101
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, TimestampType, fromJavaTimestamp, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 13, endtime), TimestampType), true, false) AS endtime#102
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:215)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:197)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:340)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: org.apache.spark.unsafe.types.UTF8String is not a valid external type for schema of string
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.StaticInvoke_2$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.writeFields_0_1$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:211)
	... 19 more

**Comment by nightscape** [comment]
@krhemanth this looks like a Spark Cassandra issue: https://stackoverflow.com/questions/63476293/spark-read-data-from-cassandra-error-org-apache-spark-unsafe-types-utf8string-is
