### ISSUE TITLE
[BUG]  NoSuchMethodError: org.apache.spark.sql.catalyst.util.FailureSafeParser when reading a folder

### ISSUE THREAD

**Issue by sevann71** [crealytics/spark-excel#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I am trying to use the last version of the library on a Databricks cluster to read a folder directly in excel format.
Here the stacktrace :

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 7.0 failed 4 times, most recent failure: Lost task 0.3 in stage 7.0 (TID 27) (10.131.243.108 executor 0): java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.util.FailureSafeParser.<init>(Lscala/Function1;Lorg/apache/spark/sql/catalyst/util/ParseMode;Lorg/apache/spark/sql/types/StructType;Ljava/lang/String;)V
	at com.crealytics.spark.v2.excel.ExcelParser$.parseIterator(ExcelParser.scala:423)
	at com.crealytics.spark.v2.excel.ExcelPartitionReaderFactory.readFile(ExcelPartitionReaderFactory.scala:75)
	at com.crealytics.spark.v2.excel.ExcelPartitionReaderFactory.buildReader(ExcelPartitionReaderFactory.scala:61)
	at org.apache.spark.sql.execution.datasources.v2.FilePartitionReaderFactory.$anonfun$createReader$1(FilePartitionReaderFactory.scala:30)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.sql.execution.datasources.v2.FilePartitionReader.getNextReader(FilePartitionReader.scala:99)
	at org.apache.spark.sql.execution.datasources.v2.FilePartitionReader.next(FilePartitionReader.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.hasNext(DataSourceRDD.scala:94)
	at org.apache.spark.sql.execution.datasources.v2.MetricsIterator.hasNext(DataSourceRDD.scala:131)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:80)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:155)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:156)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:125)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:95)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:826)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1670)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:829)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:684)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2984)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2931)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2925)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2925)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1345)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1345)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1345)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3193)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3134)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3122)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1107)
	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2628)
	at org.apache.spark.sql.execution.collect.Collector.runSparkJobs(Collector.scala:266)
	at org.apache.spark.sql.execution.collect.Collector.collect(Collector.scala:276)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:81)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:87)
	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:75)
	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:62)
	at org.apache.spark.sql.execution.ResultCacheManager.collectResult$1(ResultCacheManager.scala:587)
	at org.apache.spark.sql.execution.ResultCacheManager.computeResult(ResultCacheManager.scala:596)
	at org.apache.spark.sql.execution.ResultCacheManager.$anonfun$getOrComputeResultInternal$1(ResultCacheManager.scala:542)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResultInternal(ResultCacheManager.scala:541)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:438)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:417)
	at org.apache.spark.sql.execution.SparkPlan.executeCollectResult(SparkPlan.scala:422)
	at org.apache.spark.sql.Dataset.collectResult(Dataset.scala:3132)
	at org.apache.spark.sql.Dataset.$anonfun$collectResult$1(Dataset.scala:3123)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3930)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:209)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:356)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:160)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:958)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:115)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:306)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3928)
	at org.apache.spark.sql.Dataset.collectResult(Dataset.scala:3122)
	at com.databricks.backend.daemon.driver.OutputAggregator$.withOutputAggregation0(OutputAggregator.scala:268)
	at com.databricks.backend.daemon.driver.OutputAggregator$.withOutputAggregation(OutputAggregator.scala:102)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$getResultBufferInternal$3(ScalaDriverLocal.scala:345)
	at scala.Option.map(Option.scala:230)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$getResultBufferInternal$1(ScalaDriverLocal.scala:325)
	at scala.Option.map(Option.scala:230)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.getResultBufferInternal(ScalaDriverLocal.scala:289)
	at com.databricks.backend.daemon.driver.DriverLocal.getResultBuffer(DriverLocal.scala:715)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:267)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$11(DriverLocal.scala:602)
	at com.databricks.logging.Log4jUsageLoggingShim$.$anonfun$withAttributionContext$1(Log4jUsageLoggingShim.scala:28)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:94)
	at com.databricks.logging.Log4jUsageLoggingShim$.withAttributionContext(Log4jUsageLoggingShim.scala:26)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:205)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:204)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:60)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:240)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:225)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:60)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:579)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:615)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:607)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:526)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:561)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:431)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:374)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:225)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.util.FailureSafeParser.<init>(Lscala/Function1;Lorg/apache/spark/sql/catalyst/util/ParseMode;Lorg/apache/spark/sql/types/StructType;Ljava/lang/String;)V
	at com.crealytics.spark.v2.excel.ExcelParser$.parseIterator(ExcelParser.scala:423)
	at com.crealytics.spark.v2.excel.ExcelPartitionReaderFactory.readFile(ExcelPartitionReaderFactory.scala:75)
	at com.crealytics.spark.v2.excel.ExcelPartitionReaderFactory.buildReader(ExcelPartitionReaderFactory.scala:61)
	at org.apache.spark.sql.execution.datasources.v2.FilePartitionReaderFactory.$anonfun$createReader$1(FilePartitionReaderFactory.scala:30)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.sql.execution.datasources.v2.FilePartitionReader.getNextReader(FilePartitionReader.scala:99)
	at org.apache.spark.sql.execution.datasources.v2.FilePartitionReader.next(FilePartitionReader.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.hasNext(DataSourceRDD.scala:94)
	at org.apache.spark.sql.execution.datasources.v2.MetricsIterator.hasNext(DataSourceRDD.scala:131)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:80)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:155)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:156)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:125)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:95)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:826)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1670)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:829)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:684)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

No such method is usually linked with a compatibility issue but i have tried some different configuration and always the same problem.

I want to use the library in pyspark but i have tried in scala too and same issue.

It is ok when i am using "com.crealytics.spark.excel" just for one file.

Thanks a lot.

### Steps To Reproduce

%scala
val df = spark.read
        .format("excel")
        .option("header", "true")
        .option("inferSchema", "true")
        .load("s3://bucket/prefix/")

display(df)

%python
df = (spark
        .read
        .format("excel")
        .option("header", "true")
        .option("inferSchema", "true")
        .load("s3://bucket/prefix/")
       )

display(df)

### Environment

```markdown
- Spark version: 3.2.1
- Spark-Excel version: 3.2.1_0.17.0 scala 2.12
- OS: Databricks cluster
- Cluster environment : 10.4 LTS Photon
```

**Comment by nightscape** [comment]
Thanks for the perfect bug report!
Looks like an incompatibility between Spark and spark-excel, though the versions you specified seem to line up nicely.
I'm clueless how this one is coming about though...
@quanghgx do you have an idea?
@sevann71 could you try 0.16.x to see if the error occurs there as well? We just merged a few bigger changes in 0.17.0, so it would be great to know if this issue was introduced with the changes or existed before.

**Comment by sevann71** [comment]
Hi @nightscape , thanks for the answer.
Already tested on 0.16.x and, unfortunately, same issue appears.

Anyway, thanks a lot for this quick feedback.

**Comment by quanghgx** [comment]
This looks strange to me also.

- It seems this is not related to s3: path
- The versions look also fine as @nightscape mentioned, the binary package is from CI/CD: https://github.com/crealytics/spark-excel/blob/main/.github/workflows/ci.yml#L10
- And also the stack trace (detail below)

A. `Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.util.FailureSafeParser.(Lscala/Function1;Lorg/apache/spark/sql/catalyst/util/ParseMode;Lorg/apache/spark/sql/types/StructType;Ljava/lang/String;)V`
 
B. And code: https://github.com/crealytics/spark-excel/blob/main/src/main/scala/com/crealytics/spark/v2/excel/ExcelParser.scala#L419
 
C. And the FailureSafeParser constructor:
https://github.com/apache/spark/blob/v3.2.1/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/FailureSafeParser.scala#L26

All (A,B,C) look good and aligned with each other.

-----------------

I will try to find a Databricks with S3 storage instant this weekend and try with your version combination to reproduce this issue (I haven't used Databricks platform before).  
In the meantime, if you don't mind, can you try with the same data and versions combination on your local machine? @sevann71 
Anything that we can reproduce (like docker for example) the issue without depending on a cloud platform

**Comment by sevann71** [comment]
Ok, I have tried to launch the code from IntelliJ in java spark on my local machine with spark 3.2.0 on it and with a folder which contains xlsx files (not on S3). The code is running fine.

Maybe with default libraries installed on databricks cluster, there are some conflicts, i dont't know.

I will wait your test from databricks and we will see the result.

Thanks .

**Comment by christianknoepfle** [comment]
From here https://docs.databricks.com/release-notes/runtime/10.4.html#apache-spark I understand that on databricks they use the base spark 3.2.1 with a long list of changes added. Some of them are scheduled for spark 3.3. and not part of core 3.2.x So probably one of those changes breaks the API. Only chance is to custom compile spark excel for databricks 10.4

**Comment by nightscape** [comment]
Is there a version of the Databricks-built spark on some Maven repo? Otherwise I wouldn't know how to build against it...

**Comment by sevann71** [comment]
From my side, i don't think we could have access on the base code of Databricks-built, because i think they add their proper layer. But maybe it should be possible to dockerize it with informations on page that was sent by @christianknoepfle ? Not sure about that.
In parallel, i will raise a ticket in databricks support and i will keep in touch when i will have a response.

**Comment by sevann71** [comment]
Hi,

I think this is the problem yes.

The Databricks support answers the same thing : "We checked with the engineering team, this issue is happening because of the class constructor change from the engineering team".

The ticket has been escalated so we will see what will happen from their side.

**Comment by nightscape** [comment]
@sevann71 could you propose that they either create a second constructor with the old signature, or provide default values of `None` to the new parameters (which all seem to be `Option`-typed)?
I'm not a 100% sure if the latter will work, i.e. if a signature with additional parameters with default values compatibility-wise is identical to not having those parameters.

**Comment by christianknoepfle** [comment]
They will need to add a second ctor as you proposed. Providing default values still changes the signature of the function, thus this won't work.-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 03.05.22, 09:30 schrieb Martin Mauch ***@***.***>:

   
  @sevann71 could you propose that they either create a second constructor with the old signature, or provide default values of None to the new parameters (which all seem to be Option-typed)? I'm not a 100% sure if the latter will work, i.e. if a signature with additional parameters with default values compatibility-wise is identical to not having those parameters.

**Comment by sevann71** [comment]
I suggested them the second ctor as mentionned.

I will keep in touch.

**Comment by sevann71** [comment]
Hello guys,

Here the answer from the support :

The issue discussed in this case is fixed. I am waiting for the code to get merged. It will be part of the next maintenence release. (approx eta 05/17).
Meanwhile, you can use the below custom image based on the DBR 10.4 LTS to test it out.

custom:custom-local__10.4.x-snapshot-scala2.12__unknown__head__7c28e0c__4f39823__jenkins__7213145__format-2.lz4

How to use a custom DBR Image

Open the Javascript console in your browser (In Chrome, for example [Run JavaScript in the Console - Chrome Developers](https://developer.chrome.com/docs/devtools/console/javascript/) ) and run window.prefs.set("enableCustomSparkVersions",true) in the JS console to activate custom spark versions.
Refresh the page.
On the cluster creation page, put custom:custom-local__10.4.x-snapshot-scala2.12__unknown__head__7c28e0c__4f39823__jenkins__7213145__format-2.lz4 in the "Custom Spark Version" field.

I have tried it and seems good :)

Thanks a lot to everyone.

Sevann

**Comment by sevann71** [comment]
Hi @nightscape,
I think with default libraries installed on cluster, they did it but unfortunately, spark-excel is not (yet ? 😁) installed by default so no checks are made when a new version is able.

I close the issue and thanks for support yet.
