### ISSUE TITLE
Error when reading excel-2010

### ISSUE THREAD

**Issue by alexBaiJW** [crealytics/spark-excel#62]
If I just use apache poi to read excel-2010, that will be ok. But with spark-excel, it throws the following exception:

> The supplied data appears to be in the OLE2 Format. You are calling the part of POI that deals with OOXML (Office Open XML) Documents. You need to call a different part of POI to process this data (eg HSSF instead of XSSF)
org.apache.poi.openxml4j.exceptions.OLE2NotOfficeXmlFileException: The supplied data appears to be in the OLE2 Format. You are calling the part of POI that deals with OOXML (Office Open XML) Documents. You need to call a different part of POI to process this data (eg HSSF instead of XSSF)
	at org.apache.poi.openxml4j.opc.internal.ZipHelper.verifyZipHeader(ZipHelper.java:179)
	at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipFile(ZipHelper.java:237)
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:134)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:295)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:201)
	at com.monitorjbl.xlsx.impl.StreamingWorkbookReader.init(StreamingWorkbookReader.java:111)
	at com.monitorjbl.xlsx.impl.StreamingWorkbookReader.init(StreamingWorkbookReader.java:91)
	at com.monitorjbl.xlsx.StreamingReader$Builder.open(StreamingReader.java:263)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$openWorkbook$1.apply(ExcelRelation.scala:57)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$openWorkbook$1.apply(ExcelRelation.scala:52)
	at scala.Option.map(Option.scala:146)
	at com.crealytics.spark.excel.ExcelRelation.openWorkbook(ExcelRelation.scala:52)
	at com.crealytics.spark.excel.ExcelRelation.com$crealytics$spark$excel$ExcelRelation$$getExcerpt(ExcelRelation.scala:63)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:270)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:269)
	at scala.Option.getOrElse(Option.scala:121)
	at com.crealytics.spark.excel.ExcelRelation.inferSchema(ExcelRelation.scala:269)
	at com.crealytics.spark.excel.ExcelRelation.<init>(ExcelRelation.scala:97)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:35)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:14)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:8)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:330)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:

**Comment by alexBaiJW** [comment]
Just leave the required option, and it runs ok.
                

> .option("sheetName",getFirstSheetName(file)) // Required
    .option("useHeader", "true") // Required

**Comment by hnbian** [comment]
[new 2.txt](https://github.com/crealytics/spark-excel/files/2934017/new.2.txt)
SparkVersion 2.4.0
scalaVersion 2.12.8
我设置了
.option("sheetName",getFirstSheetName(file)) // Required
.option("useHeader", "true") // Required
但是错误依旧存在。

**Comment by zochunphy** [comment]
do you resolve the question?

**Comment by zochunphy** [comment]
我也碰到同样的问题
