### ISSUE TITLE
[BUG] writing hdfs file error when I use V2 read from hdfs file

### ISSUE THREAD

**Issue by qijinkui** [crealytics/spark-excel#672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Dataset<Row> dataset = sparkSession
                .read()
                .format("delta")
                .schema(getSchema(dataSetExtractorDO.getStructures()))
                .option("header", "true")
                .option("maxRowsInMemory", 20)
                .load("hdfs file path");

        dataset.write().format("delta").mode(SaveMode.Overwrite).option("overwriteSchema", "true").save("hdfs file path");

### Expected Behavior

WARN TaskSetManager: Lost task 0.0 in stage 6.0 (TID 56) (working3 executor 2): java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.List$SerializationProxy to field org.apache.spark.rdd.RDD.dependencies_ of type scala.collection.Seq in instance of org.apache.spark.rdd.MapPartitionsRDD
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2301)
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1431)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2437)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)

### Steps To Reproduce

Dataset<Row> dataset = sparkSession
                .read()
                .format("delta")
                .schema(getSchema(dataSetExtractorDO.getStructures()))
                .option("header", "true")
                .option("maxRowsInMemory", 20)
                .load("hdfs file path");

        dataset.write().format("delta").mode(SaveMode.Overwrite).option("overwriteSchema", "true").save("hdfs file path");

But if I use V1, there will be no abnormal behavior

### Environment

```markdown
- Spark version:3.2.1
- Spark-Excel version:3.2.1_0.17.1
- OS:Linux SmartETL-001 5.4.0-1073-azure #76~18.04.1-Ubuntu SMP Thu Mar 10 11:17:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Cluster environment
```

**Comment by nightscape** [comment]
Not sure what this has to do with spark-excel, as you're using `.format("delta")`?

**Comment by qijinkui** [comment]
But if I use V1, there will be no abnormal behavior
It is found from the source code that V1 performs the toList operation for dataRows， But v2 does not
However, writing to hdfs in v1 and v2 is successful
So I guess delta is incompatible with v2 version
