### ISSUE TITLE
Facing isuue while reading xlsx.

### ISSUE THREAD

**Issue by TridevNS** [crealytics/spark-excel#70]
18/06/20 15:22:47 INFO util.Version: Elasticsearch Hadoop v6.2.2 [102cfaa226]
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Workbook.close()V
	at com.crealytics.spark.excel.ExcelRelation.com$crealytics$spark$excel$ExcelRelation$$getExcerpt(ExcelRelation.scala:81)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:270)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:269)
	at scala.Option.getOrElse(Option.scala:121)
	at com.crealytics.spark.excel.ExcelRelation.inferSchema(ExcelRelation.scala:269)
	at com.crealytics.spark.excel.ExcelRelation.<init>(ExcelRelation.scala:97)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:35)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:14)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:8)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:330)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:135)
	at fire.samplecode.ReadExcel$.main(ReadExcel.scala:31)
	at fire.samplecode.ReadExcel.main(ReadExcel.scala)
18/06/20 15:23:02 INFO spark.SparkContext: Invoking stop() from shutdown hook
18/06/20 15:23:02 INFO server.ServerConnector: Stopped ServerConnector@200a26bc{HTTP/1.1}{0.0.0.0:4040}

**Comment by nightscape** [comment]
Looks like a library compatibility problem.
Are you using the latest version of spark-excel?
Do you have another version of Apache POI on the classpath for some reason?

**Comment by TridevNS** [comment]
Thanks for your quick response..
Yes using latest verison
    <dependency>
      <groupId>com.crealytics</groupId>
      <artifactId>spark-excel_2.11</artifactId>
      <version>0.9.15</version>
    </dependency>

**Comment by nightscape** [comment]
Hey @TridevNS,

did you solve the problem?
If not, could you try 0.9.16 and if the problem persists give some more background on how you are running Spark?
