### ISSUE TITLE
[BUG] <scala.MatchError: WrappedArray()>

### ISSUE THREAD

**Issue by meimiao0730** [crealytics/spark-excel#737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

scala.MatchError: WrappedArray() (of class scala.collection.mutable.WrappedArray$ofRef)
  at com.crealytics.spark.excel.AreaDataLocator.toCell(DataLocator.scala:121)
  at com.crealytics.spark.excel.AreaDataLocator.toCell$(DataLocator.scala:120)
  at com.crealytics.spark.excel.CellRangeAddressDataLocator.toCell(DataLocator.scala:138)
  at com.crealytics.spark.excel.AreaDataLocator.$anonfun$toSheet$3(DataLocator.scala:107)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  at scala.collection.TraversableLike.map(TraversableLike.scala:286)
  at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
  at scala.collection.AbstractTraversable.map(Traversable.scala:108)
  at com.crealytics.spark.excel.AreaDataLocator.$anonfun$toSheet$2(DataLocator.scala:106)
  at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
  at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
  at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)
  at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
  at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
  at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
  at scala.collection.AbstractIterator.to(Iterator.scala:1431)
  at scala.collection.TraversableOnce.toList(TraversableOnce.scala:350)
  at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:350)
  at scala.collection.AbstractIterator.toList(Iterator.scala:1431)
  at com.crealytics.spark.excel.AreaDataLocator.toSheet(DataLocator.scala:104)
  at com.crealytics.spark.excel.AreaDataLocator.toSheet$(DataLocator.scala:96)
  at com.crealytics.spark.excel.CellRangeAddressDataLocator.toSheet(DataLocator.scala:138)
  at com.crealytics.spark.excel.ExcelFileSaver.sheet$1(ExcelFileSaver.scala:33)
  at com.crealytics.spark.excel.ExcelFileSaver.writeToWorkbook$1(ExcelFileSaver.scala:37)
  at com.crealytics.spark.excel.ExcelFileSaver.save(ExcelFileSaver.scala:45)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:54)
  at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
  at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:110)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
  at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:110)
  at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
  at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)
  at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)
  at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)
  at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:128)
  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:848)
  at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:382)
  at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:355)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:239) 

### Environment

```markdown
- Spark version: 3.2.1
- Spark-Excel version: 3.2.1_0.17.1
- OS: Macos
- Cluster environment
```

**Comment by meimiao0730** [comment]
Arrays type look like not supported .
