### ISSUE TITLE
Not able to read excel from hadoop location

### ISSUE THREAD

**Issue by raviuiit** [crealytics/spark-excel#8]
Hi,

When I am trying to read this Excel from Hadoop using this API, it's giving file not found. As an API to be compatible with SPARK this should work flawlessly with Hadoop files. Please look into the issue.
**Code Snippet**
 DataFrame df = sqlContext.read().format("com.crealytics.spark.excel").option("location", "hdfs:////localhost:54310/home/impadmin/abc.xlsx").
         option("sheetName", "Sheet1")
         .option("useHeader", "true").option("treatEmptyValuesAsNulls", "true").option("inferSchema", "true")
         .option("addColorColumns", "true").load();
  
**Exception:**       
java.io.FileNotFoundException: hdfs:/localhost:54310/home/impadmin/StreamAnalytix/uploadjar/AMEX.csv (No such file or dir
ectory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at com.crealytics.spark.excel.ExcelRelation.<init>(ExcelRelation.scala:28)
        at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:31)
        at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:7)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)

**Comment by nightscape** [comment]
Ah, sorry, I didn't update the README for version 0.8.3.
Try that version, it should be able to read from Hadoop because of this: https://github.com/crealytics/spark-excel/pull/5

**Comment by raviuiit** [comment]
Hi,

When i am trying to use 0.8.3 api as suggested by you for any column x i am getting an additional column x_color. Can you please help me, how can i remove these unnecessary columns.

sample schema generated by your API:

root
 |-- name: string (nullable = true)
 |-- age: double (nullable = true)
 |-- location: string (nullable = true)
 |-- salary: double (nullable = true)
 |-- name_color: string (nullable = true)
 |-- age_color: string (nullable = true)
 |-- location_color: string (nullable = true)
 |-- salary_color: string (nullable = true)

**Comment by nightscape** [comment]
See the [`addColorColumns` option in the README](https://github.com/crealytics/spark-excel#scala-api).

**Comment by raviuiit** [comment]
Getting this exception when trying to fetch the first row out of data frame
[xyz.xlsx](https://github.com/crealytics/spark-excel/files/1044761/xyz.xlsx)


PFA the excel file.

root
 |-- name: string (nullable = true)
 |-- age: double (nullable = true)
 |-- location: string (nullable = true)
 |-- salary: double (nullable = true)
 
Exception in thread "main" java.lang.RuntimeException: Unknown cell type 2 for TRUE()
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$1$$anonfun$3.apply(ExcelRelation.scala:66)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$1$$anonfun$3.apply(ExcelRelation.scala:60)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$1$$anonfun$apply$2.apply(ExcelRelation.scala:82)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$1$$anonfun$apply$2.apply(ExcelRelation.scala:77)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$5$$anonfun$apply$3.apply(ExcelRelation.scala:86)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$5$$anonfun$apply$3.apply(ExcelRelation.scala:86)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)


Code:
DataFrame df = sqlContext.read().format("com.crealytics.spark.excel").option("location", "hdfs://localhost:54310/home/impadmin/xyz.xlsx")
                .option("sheetName", "Sheet1").option("useHeader", "true").option("treatEmptyValuesAsNulls", "true").option("inferSchema", "true")
                .option("addColorColumns", "false").load();
System.out.println("************ " + df.first());

**Comment by nightscape** [comment]
Hey @raviuiit, can you create a new issue if it's a different problem?
